"""
02_checks.py -- NISR/Harmonize: independent verification of Harmonized/ -> logs/checks_report.txt

  A. No data loss: every harmonised file has exactly the rows and all the native columns of its source.
  B. Keys: h_hhkey unique per household within (survey, wave [, interview]); h_pkey unique per person.
  C. Concepts recomputed independently from the native items (second route) and compared with h_*:
     LFS status1 -> h_lfstatus (exact); Census 2012 rp2024 -> h_lfstatus; EICV4 lfs6 -> h_lfstatus;
     h_sex == sex; relation: exactly one head per household in >= 99% of households.
  D. Cross-dataset table (informational): weighted employment-to-population ratio of persons 16+ per
     dataset and wave, with the definition code -- the numbers are NOT comparable across definitions.
"""
import json, sys
import numpy as np, pandas as pd
from harmonize_helpers import out_dir, db_root, read_dta, read_meta, get_logger, LOGS

log = get_logger("02_checks"); P_OUT = out_dir(); summ = json.load(open(LOGS / "harmonize_summary.json"))
report = ["# Harmonization checks report", "", "Generated by 02_checks.py.", ""]; fails = 0
def row(section, name, ours, ref, tol=0.0, fmt="{:,.0f}"):
    global fails
    ok = None if ref is None else abs(float(ours) - float(ref)) <= tol * max(1.0, abs(float(ref)))
    fails += (ok is False)
    report.append(f"| {section} | {name} | {fmt.format(ours)} | {'' if ref is None else fmt.format(ref)} | {'PASS' if ok else ('n/a' if ok is None else '**FAIL**')} |")

report += ["## A. No data loss (rows and native columns of the source file are all present)", "", "| section | statistic | harmonised | source | result |", "|---|---|---:|---:|---|"]
for out, info in summ["files"].items():
    if info.get("skipped"): report.append(f"| A | {out} | skipped ({info['skipped']}) | | n/a |"); continue
    src = db_root() / info["source"]
    ms, mo = read_meta(src), read_meta(P_OUT / out)
    row("A", f"{out} rows", mo.number_rows, ms.number_rows)
    missing_cols = [c for c in ms.column_names if c not in mo.column_names]
    row("A", f"{out} native columns present", len(ms.column_names) - len(missing_cols), len(ms.column_names))
    if missing_cols: log.error("%s lost columns: %s", out, missing_cols[:10])

report += ["", "## B. Keys", "", "| section | statistic | harmonised | reference | result |", "|---|---|---:|---:|---|"]
for out, info in summ["files"].items():
    if info.get("skipped") or info.get("unit") not in ("person", "household", "woman", "child", "establishment"): continue
    cols = [c for c in ("h_hhkey", "h_pkey", "hhid", "pid", "interview", "wave", "survey") if c in read_meta(P_OUT / out).column_names]
    if "h_hhkey" not in cols: continue
    df, _, _ = read_dta(P_OUT / out, usecols=cols)
    hk = df.loc[df["h_hhkey"] != "", "h_hhkey"]
    if info["unit"] == "household": row("B", f"{out}: h_hhkey unique (household file)", hk.nunique(), len(hk))
    if "h_pkey" in df.columns and info["unit"] == "person":
        pk = df.loc[df["h_pkey"] != "", "h_pkey"]; d = int(pk.duplicated().sum())
        row("B", f"{out}: duplicate h_pkey (NISR's own duplicate person numbers, informational)", d, None)
    del df

report += ["", "## C. Concepts recomputed independently vs h_* (second route)", "", "| section | statistic | harmonised | independent | result |", "|---|---|---:|---:|---|"]
def load(out, cols):
    m = read_meta(P_OUT / out); return read_dta(P_OUT / out, usecols=[c for c in cols if c in m.column_names])[0]
# LFS
if "H_LFS_person.dta" in summ["files"] and not summ["files"]["H_LFS_person.dta"].get("skipped"):
    d = load("H_LFS_person.dta", ["wave", "sex", "h_sex", "status1", "h_lfstatus", "h_employed", "a02", "h_relation", "h_hhkey", "wt", "age", "h_lfs_def"])
    row("C", "LFS: h_sex == sex on every row", int((d["h_sex"].astype("float") == d["sex"].astype("float")).sum()), int(d["sex"].notna().sum()))
    row("C", "LFS: h_lfstatus == status1 (all years)", int((d["h_lfstatus"].astype("float") == d["status1"].astype("float")).sum()), int(d["status1"].notna().sum()))
    row("C", "LFS: h_employed == (status1 == 1)", int(((d["h_employed"] == 1) == (d["status1"] == 1)).sum()), len(d))
    heads = d[d["h_hhkey"] != ""].groupby("h_hhkey")["h_relation"].apply(lambda s: int((s == 1).sum()))
    row("C", "LFS: household-interviews with exactly one head (h_relation == 1), share x 1000", 1000 * heads.eq(1).mean(), 1000, 0.01)
    del d
# Census
if "H_Census_person.dta" in summ["files"] and not summ["files"]["H_Census_person.dta"].get("skipped"):
    d = load("H_Census_person.dta", ["wave", "sex", "h_sex", "rp2024", "h_lfstatus", "p02", "p02_v2", "h_relation", "h_hhkey", "collective", "p21_v2", "h_marital", "p26", "p29_v2", "p06", "age"])
    row("C", "Census: h_sex == sex", int((d["h_sex"].astype("float") == d["sex"].astype("float")).sum()), int(d["sex"].notna().sum()))
    c12 = d[d["wave"] == "2012"]; ind = c12["rp2024"].map({1: 1, 2: 2, 3: 2, 4: 3, 5: 3, 6: 3, 7: 3, 9: 3})
    row("C", "Census 2012: h_lfstatus == independent recode of rp2024", int((c12["h_lfstatus"].astype("float") == ind.astype("float")).sum()), int(ind.notna().sum()))
    c02 = d[d["wave"] == "2002"]; ind = c02["p21_v2"].map({1: 1, 2: 2, 3: 2, **{k: 3 for k in (4, 5, 6, 7, 8)}})
    row("C", "Census 2002: h_lfstatus == independent recode of p21", int((c02["h_lfstatus"].astype("float") == ind.astype("float")).sum()), int(ind.notna().sum()))
    ordinary = d[(d["h_hhkey"] != "") & (d["collective"].fillna(0) == 0)]
    heads = ordinary.groupby("h_hhkey")["h_relation"].apply(lambda s: int((s == 1).sum()))
    row("C", "Census: private households with exactly one head, share x 1000", 1000 * heads.eq(1).mean(), 1000, 0.005)
    for w, src, mp in (("2022", "p06", {6: 1, 1: 2, 2: 2, 3: 2, 4: 3, 5: 3, 7: 4}), ("2012", "p29_v2", {1: 1, 2: 2, 3: 3, 5: 3, 4: 4})):
        g = d[d["wave"] == w]; ind = g[src].map(mp)
        row("C", f"Census {w}: h_marital == independent recode of {src}", int((g["h_marital"].astype("float") == ind.astype("float")).sum()), int(ind.notna().sum()))
    del d
# EICV
if "H_EICV_person.dta" in summ["files"] and not summ["files"]["H_EICV_person.dta"].get("skipped"):
    m = read_meta(P_OUT / "H_EICV_person.dta"); lf = [c for c in m.column_names if c.startswith("lfs6")]
    d = load("H_EICV_person.dta", ["wave", "sex", "h_sex", "h_lfstatus", "h_relation", "h_hhkey", "econstatus"] + lf)
    row("C", "EICV: h_sex == sex", int((d["h_sex"].astype("float") == d["sex"].astype("float")).sum()), int(d["sex"].notna().sum()))
    if lf:
        g = d[d["wave"] == "EICV4_CS"]; ind = pd.to_numeric(g[lf[0]], errors="coerce").map({1: 1, 2: 2, 3: 3})
        row("C", "EICV4: h_lfstatus == independent recode of lfs6", int((g["h_lfstatus"].astype("float") == ind.astype("float")).sum()), int(ind.notna().sum()))
    if "econstatus" in d.columns:
        g = d[d["wave"].isin(["EICV1", "EICV2"])]; ind = pd.to_numeric(g["econstatus"], errors="coerce").map({1: 1, 2: 2, 3: 3, 5: 3})
        row("C", "EICV1/2: h_lfstatus == independent recode of econstatus", int((g["h_lfstatus"].astype("float") == ind.astype("float")).sum()), int(ind.notna().sum()))
    heads = d[d["h_hhkey"] != ""].groupby("h_hhkey")["h_relation"].apply(lambda s: int((s == 1).sum()))
    row("C", "EICV: households with exactly one head, share x 1000", 1000 * heads.eq(1).mean(), 1000, 0.01)
    del d

report += ["", "## D. Weighted employment-to-population ratio, persons aged 16+ (informational: definitions differ, see h_lfs_def)", "",
           "| section | dataset / wave | h_lfs_def | employed 16+ / population 16+ with a status (%) | employed persons (weighted; LFS annual weights already average the rounds) | result |", "|---|---|---|---:|---:|---|"]
for out in ("H_LFS_person.dta", "H_Census_person.dta", "H_EICV_person.dta", "H_AHS_person.dta"):
    if out not in summ["files"] or summ["files"][out].get("skipped"): continue
    d = load(out, ["wave", "age", "wt", "h_employed", "h_lfs_def", "interview", "year"])
    d = d[(pd.to_numeric(d["age"], errors="coerce") >= 16) & d["h_employed"].notna()]
    for w, g in d.groupby("wave"):
        wt = g["wt"].astype("float"); rate = 100 * (wt * (g["h_employed"] == 1)).sum() / wt.sum(); emp = (wt * (g["h_employed"] == 1)).sum()
        report.append(f"| D | {out[2:-4]} {w} | {int(g['h_lfs_def'].dropna().iloc[0]) if g['h_lfs_def'].notna().any() else ''} | {rate:.1f} | {emp:,.0f} | n/a |")
    del d
report += ["", f"**{fails} check(s) failed.**" if fails else "**All checks passed.**"]
(LOGS / "checks_report.txt").write_text("\n".join(report)); log.info("\n" + "\n".join(report))
if fails: sys.exit(f"{fails} check(s) failed -- see logs/checks_report.txt")
log.info("02_checks done")
