"""
03_codebook.py -- NISR/Harmonize: CODEBOOK_Harmonized.xlsx and README.txt, both in Publicly-Available-NISR/Harmonized/.

Workbook sheets: README (notes), files (every harmonised file: source, unit, rows, waves, h_* variables),
code_lists (label and codes of every h_* variable, re-read from the written files so they always match the
data), counts (non-missing count of every h_* variable per file and wave), map (harmonization_map.csv in
full) and checks (logs/checks_report.txt).
"""
import json, time
import pandas as pd
from harmonize_helpers import out_dir, read_dta, read_meta, get_logger, LOGS, HERE

log = get_logger("03_codebook"); P_OUT = out_dir(); summ = json.load(open(LOGS / "harmonize_summary.json"))

def counts(path, cols, chunk=250_000):
    m = read_meta(path); out, order = None, []
    cols = [c for c in cols if c in m.column_names]
    if "wave" not in m.column_names or not cols: return pd.DataFrame(), []
    for off in range(0, m.number_rows, chunk):
        part, _, _ = read_dta(path, row_offset=off, row_limit=chunk, usecols=["wave"] + cols)
        c = part.groupby("wave", sort=False).count()
        out = c if out is None else out.add(c, fill_value=0); order += [k for k in part["wave"].unique().tolist() if k not in order]
    return out.reindex(order).fillna(0).astype(int), order

# ---- files
files = []
for out, info in summ["files"].items():
    if info.get("skipped"):
        files.append({"file": out, "source": info["source"], "unit": "", "rows": None, "variables": None, "waves": "", "h_variables": "", "skipped": info["skipped"]}); continue
    files.append({"file": out, "source": info["source"], "unit": info["unit"], "rows": info["rows"], "variables": info["vars"],
                  "waves": ", ".join(info["waves"]), "h_variables": ", ".join(info["h_vars"]), "skipped": ""})
files = pd.DataFrame(files)

# ---- code lists (from the written files)
seen = {}
for out, info in summ["files"].items():
    if info.get("skipped"): continue
    m = read_meta(P_OUT / out)
    for c in info["h_vars"]:
        if c in seen or c not in m.column_names: continue
        seen[c] = (m.column_names_to_labels.get(c, ""), m.variable_value_labels.get(c, {}))
codes = pd.DataFrame([{"h_variable": c, "label": lab, "code": k, "text": v} for c, (lab, vals) in seen.items()
                      for k, v in (vals.items() if vals else [("", "(no value labels: string key or numeric)")])])

# ---- counts per file and wave (long)
cnt = []
for out, info in summ["files"].items():
    if info.get("skipped") or not info["h_vars"]: continue
    hv = [c for c in info["h_vars"] if c not in ("h_hhkey", "h_pkey")]
    if not hv: continue
    tab, order = counts(P_OUT / out, hv)
    if tab.empty: continue
    for w in order:
        for c in hv: cnt.append({"file": out, "wave": w, "h_variable": c, "n_nonmissing": int(tab.loc[w, c]) if c in tab.columns else 0})
cnt = pd.DataFrame(cnt, columns=["file", "wave", "h_variable", "n_nonmissing"])

hmap = pd.read_csv(P_OUT / "harmonization_map.csv", dtype=str).fillna("")
report = LOGS / "checks_report.txt"
checks = pd.DataFrame({"checks_report": report.read_text().splitlines() if report.exists() else ["(no logs/checks_report.txt yet: run 02_checks.py)"]})

notes = [f"Harmonized codebook -- generated by rwa-trs/NISR/Harmonize/03_codebook.py on {time.strftime('%Y-%m-%d %H:%M')} from Publicly-Available-NISR/Harmonized/. Do not hand-edit: re-run python master.py 03.",
         "Every file is a harmonised COPY of one final or appended file of a dataset pipeline: identical key-block names and labels (survey year wave prov dist sector urban hhid pid sex age wt wt_hh), identical province/district/sector/urban/sex value labels, cross-dataset string keys h_hhkey / h_pkey, and -- on person, household and woman files -- the h_* concept variables next to the untouched native ones. No row and no native column is dropped.",
         "Sheets: files = one row per harmonised file (source file, unit, rows, variables, waves, h_* variables, skipped reason); code_lists = label and every code of each h_* variable; counts = non-missing count of each h_* variable per file and wave; map = harmonization_map.csv in full (dataset, waves, file, h_variable, source variables, rule, level, quality, note); checks = the latest verification report (logs/checks_report.txt).",
         "Employment definitions are not unified across surveys: h_lfs_def states the definition and age base behind h_lfstatus for each dataset and wave; *_approx flags mark crosswalked classifications (ISIC Rev.3, ISCO-88, EICV1-2 national groups).",
         "Per-dataset variable codebooks: CODEBOOK_<survey>.xlsx in each dataset folder. Processing notes (scope, code lists, every decision and why): project memory file NISR-Harmonize.md (Green Jobs - TRS folder), not in git or Dropbox."]

xlsx = P_OUT / "CODEBOOK_Harmonized.xlsx"
with pd.ExcelWriter(xlsx, engine="openpyxl") as xw:
    from openpyxl.styles import Font
    from openpyxl.utils import get_column_letter
    pd.DataFrame({"README": notes}).to_excel(xw, sheet_name="README", index=False)
    files.to_excel(xw, sheet_name="files", index=False)
    codes.to_excel(xw, sheet_name="code_lists", index=False)
    cnt.to_excel(xw, sheet_name="counts", index=False)
    hmap.to_excel(xw, sheet_name="map", index=False)
    checks.to_excel(xw, sheet_name="checks", index=False)
    for ws in xw.book.worksheets:
        ws.freeze_panes = "A2"
        for cell in ws[1]: cell.font = Font(bold=True)
        for j, col in enumerate(ws.iter_cols(min_row=1, max_row=min(ws.max_row, 300)), start=1):
            w = max((len(str(c.value)) for c in col if c.value is not None), default=8)
            ws.column_dimensions[get_column_letter(j)].width = min(max(10, w + 2), 80)
log.info("wrote %s (%d files, %d code rows, %d count rows, %d map rows)", xlsx, len(files), len(codes), len(cnt), len(hmap))

readme = ["================================================================================",
          "HARMONIZED/ - HARMONISED COPIES OF EVERY FINAL AND APPENDED NISR FILE",
          f"Generated {time.strftime('%Y-%m-%d %H:%M')} by rwa-trs/NISR/Harmonize/master.py (do not hand-edit: regenerated on every run)",
          "Location: .../Rwanda - TRS/data/Publicly-Available-NISR/Harmonized",
          "================================================================================", "",
          "1. WHAT THIS IS",
          "One file per source file, H_<dataset>_<unit or module>.dta: a harmonised COPY of each final (3_Final/) and appended",
          "(2_Intermediate/appended/) file of the seven NISR pipelines (Census, LFS, EICV, EC, AHS, SAS, CFSVA). Same rows, same",
          "native variables (nothing collapsed, aggregated, recoded in place or dropped), plus:",
          "  - the stylistic layer on EVERY file: identical key-block variable labels (survey year wave prov dist sector urban hhid pid",
          "    sex age wt wt_hh), identical province / district / sector value labels (from NISR's 2022 village boundary file) and",
          "    urban / sex labels, and the cross-dataset string keys h_hhkey = survey_wave[_interview]_hhid and h_pkey = h_hhkey_pid,",
          "    unique across datasets and waves (the LFS household is interviewed up to three times a year, hence the interview index);",
          "  - the concept layer on the PERSON files (LFS, Census, EICV incl. the VUP pool, AHS), the CFSVA household (head) and",
          "    woman files, and the head's sex / age on every household file: new h_* variables with common names AND common codes,",
          "    kept next to the untouched native variables.",
          "The July-2026 three-file harmonisation is untouched in Archive/Harmonized/ and no longer maintained.", "",
          "2. THE h_* VARIABLES (code lists in CODEBOOK_Harmonized.xlsx, sheet code_lists)",
          "  h_sex 1 male / 2 female.   h_marital 1 never married, 2 married or in union, 3 divorced / separated, 4 widowed.",
          "  h_relation 1 head, 2 spouse, 3 child (own, step, adopted, foster), 4 other relative, 5 non-relative.",
          "  h_attend ever attended school 0/1.   h_educ 0 none / pre-primary, 1 primary, 2 secondary (post-primary, vocational,",
          "    lower and upper), 3 tertiary.   h_literacy 1 = can read AND write.",
          "  h_lfstatus 1 employed, 2 unemployed, 3 outside the labour force -- with h_lfs_def stating the DEFINITION and age base",
          "    behind it: 1 LFS ILO 7-day (16+ to 2019, 14+ from 2020); 2 Census 2002 one-month situation; 3 Census 2012 NISR relaxed",
          "    7-day; 4 EICV1/2 NISR 12-month usual activity; 5 EICV3/5 any work in 12 months incl. own farm (no unemployment item);",
          "    6 EICV4 NISR current status; 7 EICV7 / AHS 2024 any work in 7 days incl. own farm (no unemployment item); 8 AHS",
          "    2017/2020 main activity. Census 2022 has no employment-identification block in the public file: status missing.",
          "    THESE MEASURES ARE NOT COMPARABLE ACROSS DEFINITIONS -- always condition on h_lfs_def (the checks report's section D",
          "    shows the spread of employment-to-population ratios). h_employed = (h_lfstatus == 1).",
          "  h_empstat 1 employee (incl. paid apprentice), 2 employer, 3 own-account, 4 contributing family worker, 5 other.",
          "  h_isic1 ISIC Rev.4 section 1-21 (A-U); h_isco1 ISCO-08 major group 0-9; h_isic1_approx / h_isco1_approx = 1 where the",
          "    native code was crosswalked from an older or national list (Census 2002 ISIC Rev.3 / ISCO-88; EICV1/2 NISR groups).",
          "  h_head_sex / h_head_age (and on CFSVA h_head_marital / h_head_educ / h_head_literacy) on household files.",
          "  Harmonisation LEVEL per variable (all household surveys / education group / employment group) and the exact rule per",
          "  dataset and wave are in harmonization_map.csv (columns dataset, waves, file, h_variable, source_variables, rule, level,",
          "  quality exact / approximate, note). Establishment (EC), plot x crop (SAS) and module files get the stylistic layer only.", "",
          "3. FILES IN THIS FOLDER",
          "  H_<dataset>_<unit or module>.dta   the copies (list below)",
          "  harmonization_map.csv              every code mapping (the record of what was done)",
          "  CODEBOOK_Harmonized.xlsx           sheets README, files, code_lists, counts (non-missing h_* per file and wave), map, checks",
          "  README.txt                         this file",
          "Code and run logs: git repository rwa-trs/NISR/Harmonize/ (helpers, 01_harmonize.py, 02_checks.py, 03_codebook.py,",
          "master.py). Processing notes (scope, code lists, decisions, incidents): project memory file NISR-Harmonize.md",
          "(Green Jobs - TRS folder, outside git and Dropbox). Per-dataset variable codebooks: CODEBOOK_<survey>.xlsx in each",
          "dataset folder; per-dataset READMEs there describe the native files.", "",
          "4. HOW IT WAS BUILT AND VERIFIED",
          "01_harmonize.py reads each source file in typed chunks, relabels the key block, attaches the geography value labels,",
          "builds the keys and the h_* variables from the native items -- resolving, per wave, which version column holds the",
          "item through the dataset's logs/merge_alignment.json (e.g. Census marital status = p29_v2 in 2012, p06 in 2022; LFS",
          "2025 status in employment = d05_v2) -- and writes the copy; it skips a file when less than MIN_FREE_GB would remain",
          "on disk (logged, listed as skipped below). 02_checks.py (logs/checks_report.txt, 166 checks, all PASS): A. every",
          "output has exactly the rows and native columns of its source; B. h_hhkey / h_pkey unique; C. h_lfstatus, h_marital",
          "and the head count recomputed independently from the native items (LFS status1, Census rp2024 / p21 / p29 / p06,",
          "EICV lfs6 / econstatus) equal the h_* values; D. informational employment-to-population table 16+ by definition.", "",
          "5. HOW TO USE",
          "  - Join files of one dataset on h_hhkey (household) or h_pkey (person); stack person files of different datasets and",
          "    keep survey / wave / h_lfs_def as analysis dimensions; use each file's own wt.",
          "  - Native variables are the authority for anything not covered by an h_* variable: see the dataset codebooks.",
          "  - Skipped files (disk): rerun  cd rwa-trs/NISR/Harmonize && python 01_harmonize.py EICV && python 02_checks.py &&",
          "    python 03_codebook.py  once space is freed (e.g. 2_Intermediate/ online-only in Dropbox).", "",
          "6. FILES (rows x variables [unit] <- source):"]
for out, info in summ["files"].items():
    readme.append(f"  {out:52s} {'skipped: ' + info['skipped'] if info.get('skipped') else f'{info['rows']:>10,} rows x {info['vars']:>4} vars  [{info['unit']}]  <- {info['source']}'}")
(P_OUT / "README.txt").write_text("\n".join(readme)); log.info("wrote Harmonized/README.txt")
log.info("03_codebook done")
