"""
03_codebook.py -- NISR/Harmonize: HARMONIZATION_CODEBOOK.md (repo) and Harmonized/README.txt (Dropbox).

Lists every harmonised file (source, unit, rows, waves, h_* variables), the code lists of the h_*
variables, non-missing counts of the h_* variables per wave, and the full harmonization map.
"""
import csv, json, time
import pandas as pd
from harmonize_helpers import out_dir, read_dta, read_meta, get_logger, LOGS, HERE

log = get_logger("03_codebook"); P_OUT = out_dir(); summ = json.load(open(LOGS / "harmonize_summary.json"))
# code lists are re-read from the written files so the codebook always matches the data
def counts(path, cols, chunk=250_000):
    m = read_meta(path); out, order = None, []
    cols = [c for c in cols if c in m.column_names]
    if "wave" not in m.column_names or not cols: return pd.DataFrame(), []
    for off in range(0, m.number_rows, chunk):
        part, _, _ = read_dta(path, row_offset=off, row_limit=chunk, usecols=["wave"] + cols)
        c = part.groupby("wave", sort=False).count()
        out = c if out is None else out.add(c, fill_value=0); order += [k for k in part["wave"].unique().tolist() if k not in order]
    return out.reindex(order).fillna(0).astype(int), order

md = ["# Harmonization codebook", "", f"Generated by `03_codebook.py` ({time.strftime('%Y-%m-%d %H:%M')}) from `Publicly-Available-NISR/Harmonized/`. Do not hand-edit; reasoning in `DECISIONS.md`, every code mapping in `harmonization_map.csv`.", "",
      "Every file is a harmonised COPY of one final or appended file of a dataset pipeline: identical key-block names and labels (`survey year wave prov dist sector urban hhid pid sex age wt wt_hh`), identical province/district/sector/urban/sex value labels, cross-dataset string keys `h_hhkey` / `h_pkey`, and -- on person, household and woman files -- the `h_*` concept variables next to the untouched native ones. No row and no native column is dropped.", "",
      "## Files", "", "| file | source | unit | rows | waves | h_* variables |", "|---|---|---|---:|---|---|"]
for out, info in summ["files"].items():
    if info.get("skipped"): md.append(f"| `{out}` | `{info['source']}` | (skipped: {info['skipped']}) | | | |"); continue
    md.append(f"| `{out}` | `{info['source']}` | {info['unit']} | {info['rows']:,} | {', '.join(info['waves'])} | {', '.join(info['h_vars'])} |")
md += ["", "## Harmonised variables and code lists", ""]
seen = {}
for out, info in summ["files"].items():
    if info.get("skipped"): continue
    m = read_meta(P_OUT / out)
    for c in info["h_vars"]:
        if c in seen or c not in m.column_names: continue
        seen[c] = (m.column_names_to_labels.get(c, ""), m.variable_value_labels.get(c, {}))
for c, (lab, vals) in seen.items():
    md.append(f"- `{c}` — {lab}" + ((": " + "; ".join(f"{k} = {v}" for k, v in vals.items())) if vals else ""))
md += ["", "## Non-missing counts of the h_* variables by wave", ""]
for out, info in summ["files"].items():
    if info.get("skipped") or not info["h_vars"]: continue
    hv = [c for c in info["h_vars"] if c not in ("h_hhkey", "h_pkey")]
    if not hv: continue
    tab, order = counts(P_OUT / out, hv)
    if tab.empty: continue
    md += [f"### `{out}`", "", "| wave | " + " | ".join(hv) + " |", "|---|" + "---:|" * len(hv)]
    for w in order: md.append(f"| {w} | " + " | ".join(f"{int(tab.loc[w, c]) if c in tab.columns else 0:,}" for c in hv) + " |")
    md.append("")
md += ["## Harmonization map", "", "| dataset | waves | file | h_variable | source | rule | level | quality | note |", "|---|---|---|---|---|---|---|---|---|"]
for r in csv.DictReader(open(P_OUT / "harmonization_map.csv")):
    md.append("| " + " | ".join(str(r[k]).replace("|", "/") for k in ("dataset", "waves", "file", "h_variable", "source_variables", "rule", "level", "quality", "note")) + " |")
(HERE / "HARMONIZATION_CODEBOOK.md").write_text("\n".join(md)); log.info("wrote HARMONIZATION_CODEBOOK.md")

readme = [f"Harmonized/  -- harmonised copies of every final and appended NISR file (generated {time.strftime('%Y-%m-%d %H:%M')} by rwa-trs/NISR/Harmonize/master.py)", "",
          "One file per source file: H_<dataset>_<unit or module>.dta. Same rows, same native variables, plus:",
          "  - identical key-block names/labels and identical geography/sex value labels across the seven datasets;",
          "  - h_hhkey / h_pkey: string household / person keys unique across datasets and waves;",
          "  - h_* concept variables (sex, marital, relationship, education, literacy, labour-force status and its definition,",
          "    status in employment, ISIC section, ISCO major group; head's sex/age on household files) on the person, household and woman files.",
          "harmonization_map.csv lists every code mapping (dataset, wave, file, h_variable, source, rule, level, quality, note).",
          "Code, DECISIONS.md, HARMONIZATION_CODEBOOK.md and logs live in the git repository rwa-trs/NISR/Harmonize/, not here.",
          "The older 3-file harmonisation of July 2026 is untouched in Archive/Harmonized/.", "", "Files:"]
for out, info in summ["files"].items():
    readme.append(f"  {out:52s} {'skipped: ' + info['skipped'] if info.get('skipped') else f'{info['rows']:>10,} rows x {info['vars']:>4} vars  [{info['unit']}]  <- {info['source']}'}")
(P_OUT / "README.txt").write_text("\n".join(readme)); log.info("wrote Harmonized/README.txt")
log.info("03_codebook done")
