"""
03_codebook.py -- NISR/Harmonize: CODEBOOK_Harmonized.xlsx and README.txt, both in Publicly-Available-NISR/Harmonisation-docs/.

Workbook sheets: README (notes), files (every harmonised file: source, unit, rows, waves, h_* variables),
code_lists (label and codes of every h_* variable, re-read from the written files so they always match the
data), counts (non-missing count of every h_* variable per file and wave), map (harmonization_map.csv in
full) and checks (logs/checks_report.txt).
"""
import json, time
import pandas as pd
from harmonize_helpers import out_dir, h_path, read_dta, read_meta, get_logger, LOGS, HERE, H_STEM, h_name

log = get_logger("03_codebook"); P_OUT = out_dir(); summ = json.load(open(LOGS / "harmonize_summary.json"))

def counts(path, cols, wave_col, chunk=250_000):
    """non-missing counts per wave; wave_col is the file's own wave column (<ds>_wave)"""
    m = read_meta(path); out, order = None, []
    cols = [c for c in cols if c in m.column_names]
    if wave_col not in m.column_names or not cols: return pd.DataFrame(), []
    for off in range(0, m.number_rows, chunk):
        part, _, _ = read_dta(path, row_offset=off, row_limit=chunk, usecols=[wave_col] + cols)
        c = part.groupby(wave_col, sort=False).count()
        out = c if out is None else out.add(c, fill_value=0); order += [k for k in part[wave_col].unique().tolist() if k not in order]
    return out.reindex(order).fillna(0).astype(int), order

# ---- files
files = []
for out, info in summ["files"].items():
    if info.get("skipped"):
        files.append({"file": out, "folder": str(h_path(out, info).parent.relative_to(h_path(out, info).parent.parent.parent)), "source": info["source"], "unit": "", "rows": None, "variables": None, "waves": "", "h_variables": "", "skipped": info["skipped"]}); continue
    files.append({"file": out, "folder": str(h_path(out, info).parent.relative_to(h_path(out, info).parent.parent.parent)), "source": info["source"], "unit": info["unit"], "rows": info["rows"], "variables": info["vars"],
                  "waves": ", ".join(info["waves"]), "h_variables": ", ".join(info["h_vars"]), "skipped": ""})
files = pd.DataFrame(files)

# ---- code lists (from the written files)
seen = {}
for out, info in summ["files"].items():
    if info.get("skipped"): continue
    m = read_meta(h_path(out, info))
    for c in info["h_vars"]:
        if c in seen or c not in m.column_names: continue
        seen[c] = (m.column_names_to_labels.get(c, ""), m.variable_value_labels.get(c, {}))
codes = pd.DataFrame([{"h_variable": c, "label": lab, "code": k, "text": v} for c, (lab, vals) in seen.items()
                      for k, v in (vals.items() if vals else [("", "(no value labels: string key or numeric)")])])

# ---- counts per file and wave (long)
cnt = []
for out, info in summ["files"].items():
    if info.get("skipped") or not info["h_vars"]: continue
    keys = {h_name(info["dataset"], h) for h in ("h_hhkey", "h_pkey")}
    hv = [c for c in info["h_vars"] if c not in keys]
    if not hv: continue
    tab, order = counts(h_path(out, info), hv, f"{info['dataset'].lower()}_wave")
    if tab.empty: continue
    for w in order:
        for c in hv: cnt.append({"file": out, "wave": w, "h_variable": c, "n_nonmissing": int(tab.loc[w, c]) if c in tab.columns else 0})
cnt = pd.DataFrame(cnt, columns=["file", "wave", "h_variable", "n_nonmissing"])

hmap = pd.read_csv(P_OUT / "harmonization_map.csv", dtype=str).fillna("")
report = LOGS / "checks_report.txt"
checks = pd.DataFrame({"checks_report": report.read_text().splitlines() if report.exists() else ["(no logs/checks_report.txt yet: run 02_checks.py)"]})

notes = [f"Harmonized codebook -- generated by rwa-trs/NISR/Harmonize/03_codebook.py on {time.strftime('%Y-%m-%d %H:%M')} from Publicly-Available-NISR/Harmonisation-docs/. Do not hand-edit: re-run python master.py 03.",
         "4_Harmonized mirrors 3_Final: one harmonised COPY of each final file of a dataset pipeline, nothing else. Every variable keeps the clean name it has in 3_Final (<dataset>_<english words>); the key block carries identical labels across datasets (<ds>_survey <ds>_year <ds>_wave <ds>_province <ds>_district <ds>_sector <ds>_urban <ds>_household_id <ds>_person_id <ds>_sex <ds>_age <ds>_weight <ds>_household_weight) and identical province/district/sector/urban/sex value labels, cross-dataset string keys <ds>_household_key / <ds>_person_key, and -- on person, household and woman files -- the harmonised concept variables next to the untouched native ones. No row and no native column is dropped.",
         "The harmonised concepts share one stem across datasets and carry the dataset prefix (lfs_labour_status, census_labour_status, eicv_labour_status ...): the prefix says where a row comes from, never that the file is harmonised. Sheets: files = one row per harmonised file (source file, unit, rows, variables, waves, harmonised variables, skipped reason); code_lists = label and every code of each harmonised variable; counts = non-missing count of each harmonised variable per file and wave; map = harmonization_map.csv in full (dataset, waves, file, h_variable, source variables, rule, level, quality, note); checks = the latest verification report (logs/checks_report.txt).",
         "Employment definitions are not unified across surveys: <ds>_labour_definition states the definition and age base behind <ds>_labour_status for each dataset and wave; the *_approx flags mark crosswalked classifications (ISIC Rev.3, ISCO-88, EICV1-2 national groups).",
         "Per-dataset variable codebooks: CODEBOOK_<survey>.xlsx in each dataset folder. Processing notes (scope, code lists, every decision and why): project memory file NISR-Harmonize.md (Green Jobs - TRS folder), not in git or Dropbox."]

xlsx = P_OUT / "CODEBOOK_Harmonized.xlsx"
with pd.ExcelWriter(xlsx, engine="openpyxl") as xw:
    from openpyxl.styles import Font
    from openpyxl.utils import get_column_letter
    pd.DataFrame({"README": notes}).to_excel(xw, sheet_name="README", index=False)
    files.to_excel(xw, sheet_name="files", index=False)
    codes.to_excel(xw, sheet_name="code_lists", index=False)
    cnt.to_excel(xw, sheet_name="counts", index=False)
    hmap.to_excel(xw, sheet_name="map", index=False)
    checks.to_excel(xw, sheet_name="checks", index=False)
    for ws in xw.book.worksheets:
        ws.freeze_panes = "A2"
        for cell in ws[1]: cell.font = Font(bold=True)
        for j, col in enumerate(ws.iter_cols(min_row=1, max_row=min(ws.max_row, 300)), start=1):
            w = max((len(str(c.value)) for c in col if c.value is not None), default=8)
            ws.column_dimensions[get_column_letter(j)].width = min(max(10, w + 2), 80)
log.info("wrote %s (%d files, %d code rows, %d count rows, %d map rows)", xlsx, len(files), len(codes), len(cnt), len(hmap))

skipped = [f for f, i in summ["files"].items() if i.get("skipped")]
readme = ["================================================================================",
          "HARMONISED COPIES OF THE FINAL NISR FILES -- <dataset>/4_Harmonized/ (data) and Harmonisation-docs/ (these documents)",
          f"Generated {time.strftime('%Y-%m-%d %H:%M')} by rwa-trs/NISR/Harmonize/master.py (do not hand-edit: regenerated on every run)",
          "Location: .../Rwanda - TRS/data/Publicly-Available-NISR/Harmonisation-docs",
          "================================================================================", "",
          "1. WHAT THIS IS",
          "4_Harmonized MIRRORS 3_Final (Matteo, 2026-09-06): one file per final file, <dataset>/4_Harmonized/H_<dataset>_<unit>.dta,",
          "a harmonised COPY of each 3_Final file of the seven NISR pipelines (Census, LFS, EICV, EC, AHS, SAS, CFSVA), stored INSIDE",
          "each dataset folder as its fourth folder. Nothing from 2_Intermediate is copied here. This Harmonisation-docs/ folder holds only",
          "the three cross-dataset documents: this README, CODEBOOK_Harmonized.xlsx and harmonization_map.csv. Same rows, same",
          "variables under the same clean names as in 3_Final (nothing collapsed, aggregated, recoded in place or dropped), plus:",
          "  - the stylistic layer on EVERY file: identical key-block variable labels (<ds>_survey <ds>_year <ds>_wave <ds>_province",
          "    <ds>_district <ds>_sector <ds>_urban <ds>_household_id <ds>_person_id <ds>_sex <ds>_age <ds>_weight <ds>_household_weight),",
          "    identical province / district / sector value labels (from NISR's 2022 village boundary file) and urban / sex labels,",
          "    and the cross-dataset string keys <ds>_household_key = survey_wave[_interview]_hhid and <ds>_person_key = that plus the person number",
          "    (the LFS household is interviewed up to three times a year, hence the interview index). The keys are BLANK where the",
          "    public file has no household id: LFS 2020 reduced rounds (32,853 persons), Census 2002 collective households (16,717),",
          "    CFSVA 2015 woman / child files (nutrition-form ids only), CFSVA 2012 children with id 0 (282). <ds>_person_key repeats for the",
          "    three LFS persons NISR numbered twice. <ds>_household_key is unique in every household file (checks, section B);",
          "  - the concept layer on the PERSON files (LFS, Census, EICV, AHS), the CFSVA household (head) and woman files, and the",
          "    head's sex / age on every household file: new variables with one stem shared across datasets AND common codes",
          "    (<ds>_labour_status, <ds>_employed, <ds>_labour_definition, <ds>_employment_status, <ds>_industry_isic (+_approx),",
          "    <ds>_occupation_isco (+_approx), <ds>_education_level, <ds>_literacy, <ds>_school_attendance, <ds>_marital_status,",
          "    <ds>_relationship_to_head, <ds>_head_sex, <ds>_head_age, <ds>_head_marital_status, <ds>_head_education_level,",
          "    <ds>_head_literacy), kept next to the untouched source variables. Sex is not repeated: <ds>_sex is already harmonised.",
          "The July-2026 three-file harmonisation is untouched in Archive/Harmonized/ and no longer maintained.", "",
          "2. THE HARMONISED VARIABLES (code lists in CODEBOOK_Harmonized.xlsx, sheet code_lists)",
          "  <ds>_sex 1 male / 2 female.   <ds>_marital_status 1 never married, 2 married or in union, 3 divorced / separated, 4 widowed.",
          "  <ds>_relationship_to_head 1 head, 2 spouse, 3 child (own, step, adopted, foster), 4 other relative, 5 non-relative.",
          "  <ds>_school_attendance ever attended school 0/1.   <ds>_education_level 0 none / pre-primary, 1 primary, 2 secondary (post-primary, vocational,",
          "    lower and upper), 3 tertiary -- a BROAD level: the source concept varies (LFS level attended / attending; Census 2002",
          "    and EICV highest class completed / attained; the map's quality field says code-exact, not concept-exact).",
          "    <ds>_literacy 1 = can read AND write.",
          "  <ds>_labour_status 1 employed, 2 unemployed, 3 outside the labour force -- with <ds>_labour_definition stating the DEFINITION and age base",
          "    behind it: 1 LFS ILO 7-day (16+ to 2019, 14+ from 2020); 2 Census 2002 one-month situation (8 'jobless / has no work'",
          "    = unemployed); 3 Census 2012 NISR relaxed 7-day (rp2024; the 'not classified' residual 9 is unemployed when available",
          "    for work, P23, otherwise outside); 4 EICV1/2 NISR 12-month usual activity; 5 EICV3/5 any work in 12 months incl. own",
          "    farm (no unemployment item; EICV3 'VUP does not exist here' counts as no work);",
          "    6 EICV4 NISR current status; 7 EICV7 / AHS 2024 any work in 7 days incl. own farm (no unemployment item); 8 AHS",
          "    2017/2020 main activity. Census 2022 has no employment-identification block in the public file: status missing.",
          "    THESE MEASURES ARE NOT COMPARABLE ACROSS DEFINITIONS -- always condition on <ds>_labour_definition (the checks report's section D",
          "    shows the spread of employment-to-population ratios). <ds>_employed = (<ds>_labour_status == 1).",
          "    WITHIN a dataset the definition is the same in every wave wherever the questionnaire allows it: LFS = NISR status1",
          "    in every year; Census 2002 and 2012 = relaxed unemployment (without work, no job-search test) in both waves;",
          "    EICV: <ds>_employed (any work in the reference period) is defined the same way in every wave, while the UNEMPLOYED",
          "    category exists only where an item supports it (EICV1/2 usual activity, EICV4 lfs6, EICV5 reason for not working;",
          "    EICV3 and EICV7 have no unemployment item: non-workers are 'outside'); AHS: main activity in 2017/2020, any work",
          "    in 2024. Compare over time within a dataset on <ds>_employed, or on <ds>_labour_status with <ds>_labour_definition held fixed.",
          "  <ds>_employment_status 1 employee (incl. paid apprentice), 2 employer, 3 own-account, 4 contributing family worker, 5 other.",
          "  <ds>_industry_isic ISIC Rev.4 section 1-21 (A-U); <ds>_occupation_isco ISCO-08 major group 0-9; <ds>_industry_isic_approx / <ds>_occupation_isco_approx = 1 where the",
          "    native code was crosswalked from an older or national list (Census 2002 ISIC Rev.3 / ISCO-88; EICV1/2 NISR groups).",
          "  <ds>_head_sex / <ds>_head_age (and on CFSVA <ds>_head_marital_status / <ds>_head_education_level / <ds>_head_literacy) on household files.",
          "  Harmonisation LEVEL per variable (all household surveys / education group / employment group) and the exact rule per",
          "  dataset and wave are in harmonization_map.csv (columns dataset, waves, file, h_variable, source_variables, rule, level,",
          "  quality exact / approximate, note). The establishment file (EC), the plot x crop and screening files (SAS) and the CFSVA", "  child and village files get the stylistic layer only (keys, labels, value labels).", "",
          "3. FILES",
          "  <dataset>/4_Harmonized/H_<dataset>_<unit>.dta      one copy per 3_Final file (list below)." + (" DECLARED LIMITATION: " + ", ".join(sorted(skipped)) + " (EICV item" if skipped else ""),
          "                                     modules, several GB each) are NOT copied while the Mac has no room for them -- use the" if skipped else "                                     Every expected copy is present (no disk skip in this run).",
          "                                     source files in Household-Living-Conditions-EICV/2_Intermediate/appended/." if skipped else "",
          "  harmonization_map.csv              every code mapping (the record of what was done)",
          "  CODEBOOK_Harmonized.xlsx           sheets README, files, code_lists, counts (non-missing harmonised per file and wave), map, checks",
          "  README.txt                         this file (the three documents above are the only content of Harmonized/)",
          "Code and run logs: git repository rwa-trs/NISR/Harmonize/ (helpers, 01_harmonize.py, 02_checks.py, 03_codebook.py,",
          "master.py). Processing notes (scope, code lists, decisions, incidents): project memory file NISR-Harmonize.md",
          "(Green Jobs - TRS folder, outside git and Dropbox). Per-dataset variable codebooks: CODEBOOK_<survey>.xlsx in each",
          "dataset folder; per-dataset READMEs there describe the native files.", "",
          "4. HOW IT WAS BUILT AND VERIFIED",
          "01_harmonize.py reads each source file in typed chunks, relabels the key block, attaches the geography value labels,",
          "builds the keys and the harmonised variables from the native items -- resolving, per wave, which version column holds the",
          "item through the dataset's logs/merge_alignment.json (e.g. Census marital status = p29_v2 in 2012, p06 in 2022; LFS",
          "2025 status in employment = d05_v2) -- and writes the copy. A preflight refuses to start when any file other than the",
          "six declared EICV skips would not fit on disk (MIN_FREE_GB), so the folder is never a mixture of old and new copies;",
          "a replaced copy is deleted before the new one is written and copies without a source file any more are removed.",
          "02_checks.py (logs/checks_report.txt; every hard check PASS on the date above -- the checks sheet of the codebook is",
          "the report): A. every expected copy exists (declared skips listed), no stray file, and every copy has exactly the",
          "rows and native columns of its CURRENT source; B. <ds>_household_key unique per household file, person-key duplicates only where",
          "NISR numbered persons twice, CFSVA woman / child keys link to the household file (2015 blank); C. concepts recomputed",
          "from the documented code lists (LFS status1 on observed rows, LFS 2024-2025 14-code relationships, Census 2012 rp2024",
          "+ P23, Census 2002 p21, EICV1/2 econstatus, EICV3 work items with the VUP item, EICV4 lfs6, EICV education sentinels",
          "never tertiary, one head per household); D. informational employment-to-population table 16+ by definition.", "",
          "5. HOW TO USE",
          "  - Join files of one dataset on <ds>_household_key (household) or <ds>_person_key (person) -- blank keys never match (section 1); stack",
          "    person files of different datasets and keep survey / wave / <ds>_labour_definition as analysis dimensions.",
          "  - wt: on person, household, establishment and plot files it sums to the population of the unit; on module / item",
          "    files (EICV services, AHS tools, CFSVA woman / child ...) it REPEATS the parent household or plot weight on every",
          "    record and is labelled so -- it is not a record-level expansion weight.",
          "  - Native variables are the authority for anything not covered by an harmonised variable: see the dataset codebooks.",
          "  - Declared skips (disk): rerun  cd rwa-trs/NISR/Harmonize && python 01_harmonize.py EICV && python 02_checks.py &&",
          "    python 03_codebook.py  once space is freed (e.g. 2_Intermediate/ online-only in Dropbox) and remove the six names",
          "    from KNOWN_SKIPS in 01_harmonize.py.", "",
          "6. FILES (folder / file: rows x variables [unit] <- source):"]
for out, info in summ["files"].items():
    folder = str(h_path(out, info).parent.relative_to(h_path(out, info).parent.parent.parent))
    readme.append(f"  {folder + '/' + out:90s} {'skipped: ' + info['skipped'] if info.get('skipped') else f'{info['rows']:>10,} rows x {info['vars']:>4} vars  [{info['unit']}]  <- {info['source']}'}")
(P_OUT / "README.txt").write_text("\n".join(readme)); log.info("wrote Harmonized/README.txt")
log.info("03_codebook done")
