"""
03_checks.py -- SAS: verification of 3_Final/SAS_pooled_plotcrop.dta -> logs/checks_report.md
  A. pooled rows vs per-wave files   B. Stata 17 recomputation   C. internal consistency of the core quantities
"""
import os, shutil, subprocess, sys
import pandas as pd
from sas_helpers import paths, get_logger, read_dta, LOGS, HERE
log = get_logger("03_checks"); P = paths()
report = ["# SAS checks report", "", "Generated by 03_checks.py.", ""]; fails = 0
def row(section, name, ours, ref, tol=0.0):
    global fails
    ok = None if ref is None else abs(float(ours) - float(ref)) <= tol * max(1.0, abs(float(ref)))
    fails += (ok is False)
    report.append(f"| {section} | {name} | {ours:,.0f} | {'' if ref is None else f'{ref:,.0f}'} | {'PASS' if ok else ('n/a' if ok is None else '**FAIL**')} |")
pc, _, _ = read_dta(P["final"] / "SAS_pooled_plotcrop.dta", usecols=["wave", "year", "season", "wt", "crop", "plot_area_ha", "crop_area_ha", "harvested_area_ha", "production_kg"])
ours = {w: {"n": len(g), "n_wt": int(g["wt"].notna().sum()), "sum_wt": g["wt"].sum(), "prod": g["production_kg"].sum(), "area": g["crop_area_ha"].fillna(g["harvested_area_ha"]).sum()} for w, g in pc.groupby("wave", sort=False)}
report += ["## A. Pooled plot x crop file by wave", "", "| section | statistic | Python | reference | result |", "|---|---|---:|---:|---|"]
for w, o in ours.items():
    row("A", f"{w} rows", o["n"], None); row("A", f"{w} rows with a weight [informational]", o["n_wt"], None); row("A", f"{w} weighted crop area (ha)", (pc.loc[pc.wave == w, "wt"] * pc.loc[pc.wave == w, "crop_area_ha"].fillna(pc.loc[pc.wave == w, "harvested_area_ha"])).sum(), None)
report += ["", "## B. Stata 17 recomputation", ""]
stata = "/Applications/Stata/StataMP.app/Contents/MacOS/stata-mp"
if not os.path.exists(stata): stata = shutil.which("stata-mp") or shutil.which("stata")
if stata:
    do, out = HERE / "stata_checks.do", LOGS / "stata_checks.csv"
    do.write_text(f'''* stata_checks.do -- recompute SAS check statistics in Stata (written by 03_checks.py)
clear all
set more off
use wave wt production_kg using "{P["final"] / "SAS_pooled_plotcrop.dta"}", clear
gen long one = 1
gen byte haswt = wt < .
collapse (sum) n=one n_wt=haswt sum_wt=wt prod=production_kg, by(wave)
export delimited using "{out}", replace
''')
    r = subprocess.run([stata, "-q", "-b", "do", str(do)], cwd=str(HERE), capture_output=True, text=True); logf = HERE / "stata_checks.log"
    if out.exists():
        st = pd.read_csv(out).set_index("wave"); report += ["| section | statistic | Python | Stata | result |", "|---|---|---:|---:|---|"]
        for w, o in ours.items():
            s = st.loc[w]; row("B", f"{w} rows", o["n"], s["n"]); row("B", f"{w} rows with weight", o["n_wt"], s["n_wt"]); row("B", f"{w} sum wt", o["sum_wt"], s["sum_wt"], 1e-6); row("B", f"{w} sum production (kg)", o["prod"], s["prod"], 1e-6)
        if logf.exists(): (LOGS / "stata_checks.log").write_text(logf.read_text()); logf.unlink()
    else: report.append(f"Stata run produced no output (rc={r.returncode})"); fails += 1
else: report.append("Stata not found -- section B skipped.")
report += ["", "## C. Internal consistency", "", "| section | statistic | Python | reference | result |", "|---|---|---:|---:|---|"]
bad = int(((pc["crop_area_ha"] > pc["plot_area_ha"] * 1.05) & pc["crop_area_ha"].notna() & pc["plot_area_ha"].notna()).sum())
row("C", "rows with crop area > plot area (+5%) [count, informational]", bad, None)
row("C", "rows with negative production", int((pc["production_kg"] < 0).sum()), 0)
report += ["", f"**{fails} check(s) failed.**" if fails else "**All checks passed.**"]
(LOGS / "checks_report.md").write_text("\n".join(report)); log.info("\n" + "\n".join(report))
if fails: sys.exit(f"{fails} check(s) failed -- see logs/checks_report.md")
log.info("03_checks done")
