"""
03_checks.py -- SAS: verification of 3_Final/ and 2_Intermediate/appended/ -> logs/checks_report.txt
  A. pooled crop-production file vs the per-wave cleaned files (rows from the meta files), crop key complete, weights
  B. Stata 17 recomputation
  C. core quantities: plot-area plausibility, crop area <= plot area, production / harvested area == shipped yield
  D. published totals: cultivated maize area from the SCREENING crop records x plot weight vs the NISR annual reports
     (2020 A/B, 2021 A/B, 2022 A/B, 2023 A/B) -- the official cultivated-area universe
  E. module coverage (years present per canonical module), record keys (informational), crop dictionaries
     (same code = same text within a crop list generation), cross-wave coding compatibility within every pooled column
Hard checks have a reference; rows with an empty reference are informational (n/a).
"""
import difflib, json, os, re, shutil, subprocess, sys
import numpy as np, pandas as pd
from sas_helpers import paths, get_logger, read_dta, LOGS, HERE
log = get_logger("03_checks"); P = paths()
report = ["# SAS checks report", "", "Generated by 03_checks.py.", ""]; fails = 0
def row(section, name, ours, ref, tol=0.0):
    global fails
    ok = None if ref is None else abs(float(ours) - float(ref)) <= tol * max(1.0, abs(float(ref)))
    fails += (ok is False)
    report.append(f"| {section} | {name} | {ours:,.0f} | {'' if ref is None else f'{ref:,.0f}'} | {'PASS' if ok else ('n/a' if ok is None else '**FAIL**')} |")
align = json.load(open(LOGS / "merge_alignment.json"))
metas = {f.stem.replace("clean_", "").replace("_meta", ""): json.load(open(f)) for f in LOGS.glob("clean_*_meta.json")}
HDR = ["| section | statistic | Python | reference | result |", "|---|---|---:|---:|---|"]

# ---------------------------------------------------------------- A
pc, _, _ = read_dta(P["final"] / "SAS_pooled_plotcrop.dta", usecols=["wave", "year", "season", "farm_type", "segment", "holder", "plot", "crop", "wt", "plot_area_ha", "crop_area_ha", "harvested_area_ha", "production_kg", "yield_kg_ha"])
info = align["files"]["SAS_pooled_plotcrop.dta"]; wm = info.get("wave_modules", {})
ours = {w: {"n": len(g), "n_wt": int(g["wt"].notna().sum()), "sum_wt": g["wt"].sum(), "prod": g["production_kg"].sum()} for w, g in pc.groupby("wave", sort=False)}
report += ["## A. Pooled crop-production file vs the per-wave cleaned files", ""] + HDR
for w, o in ours.items():
    y, mk = wm.get(w, (None, None)); ref = metas.get(y, {}).get(mk, {}).get("rows") if y else None
    row("A", f"{w} rows == cleaned file rows", o["n"], ref)
    g = pc[pc.wave == w]
    row("A", f"{w} rows with a crop code (share x 1000; must be >= 990)", 1000 * g["crop"].notna().mean(), 1000, 0.01)
    row("A", f"{w} rows with a weight (informational; 2017-2018 LSF and part of 2020-2021 ship none)", o["n_wt"], None)
row("A", "pooled rows == sum of wave rows", len(pc), sum(o["n"] for o in ours.values()))

# ---------------------------------------------------------------- B
report += ["", "## B. Stata 17 recomputation", ""]
stata = "/Applications/Stata/StataMP.app/Contents/MacOS/stata-mp"
if not os.path.exists(stata): stata = shutil.which("stata-mp") or shutil.which("stata")
if stata:
    do, out = HERE / "stata_checks.do", LOGS / "stata_checks.csv"
    do.write_text(f'''* stata_checks.do -- recompute SAS check statistics in Stata (written by 03_checks.py)
clear all
set more off
use wave wt production_kg plot_area_ha using "{P["final"] / "SAS_pooled_plotcrop.dta"}", clear
gen long one = 1
gen byte haswt = wt < .
collapse (sum) n=one n_wt=haswt sum_wt=wt prod=production_kg (median) med_plot=plot_area_ha, by(wave)
export delimited using "{out}", replace
''')
    r = subprocess.run([stata, "-q", "-b", "do", str(do)], cwd=str(HERE), capture_output=True, text=True); logf = HERE / "stata_checks.log"
    if out.exists():
        st = pd.read_csv(out).set_index("wave"); report += ["| section | statistic | Python | Stata | result |", "|---|---|---:|---:|---|"]
        for w, o in ours.items():
            s = st.loc[w]; row("B", f"{w} rows", o["n"], s["n"]); row("B", f"{w} rows with weight", o["n_wt"], s["n_wt"]); row("B", f"{w} sum wt", o["sum_wt"], s["sum_wt"], 1e-6); row("B", f"{w} sum production (kg)", o["prod"], s["prod"], 1e-6)
            row("B", f"{w} median plot area (m2)", 1e4 * pc.loc[pc.wave == w, "plot_area_ha"].median(), 1e4 * s["med_plot"], 1e-6)
        if logf.exists(): (LOGS / "stata_checks.log").write_text(logf.read_text()); logf.unlink()
    else: report.append(f"Stata run produced no output (rc={r.returncode})"); fails += 1
else: report.append("Stata not found -- section B skipped.")

# ---------------------------------------------------------------- C
report += ["", "## C. Core quantities (CORE / CORE_SEASON map)", ""] + HDR
for w, g in pc.groupby("wave", sort=False):
    med = g["plot_area_ha"].median()
    if pd.notna(med): row("C", f"{w} median plot area (m2) -- plausible band 100-30,000 (must be inside)", 1e4 * med, 1e4 * med if 0.01 <= med <= 3 else 0)
    both = g["crop_area_ha"].notna() & g["plot_area_ha"].notna()
    if both.any(): row("C", f"{w} rows with crop area > plot area + 5% (share x 1000; must be <= 20)", 1000 * ((g["crop_area_ha"] > g["plot_area_ha"] * 1.05) & both).sum() / both.sum(), 0, 20)
    trio = g["production_kg"].notna() & g["harvested_area_ha"].gt(0) & g["yield_kg_ha"].gt(0)     # shipped yield 0 = not computed by NISR (2022 A: 1,319 rows)
    if trio.any():
        ratio = g.loc[trio, "production_kg"] / g.loc[trio, "harvested_area_ha"] / g.loc[trio, "yield_kg_ha"]
        row("C", f"{w} production / harvested area == shipped yield (share of rows within 0.1%, x 1000; must be >= 990)", 1000 * (ratio.sub(1).abs() < 1e-3).mean(), 1000, 0.01)
row("C", "rows with negative production", int((pc["production_kg"] < 0).sum()), 0)
row("C", "2019 B/C plot area shipped in ha (median 2019_B plot area, m2: ~1,258 expected)", 1e4 * pc.loc[pc.wave == "2019_B", "plot_area_ha"].median(), 1258, 0.05)
row("C", "2019 C crop area == shipped harvested area (rows within 0.1%, x 1000)", 1000 * ((pc.loc[pc.wave == "2019_C", "crop_area_ha"] / pc.loc[pc.wave == "2019_C", "harvested_area_ha"]).sub(1).abs() < 1e-3).mean(), 1000, 0.01)

# ---------------------------------------------------------------- D. published cultivated maize area (screening crop records x plot weight)
# NISR SAS annual reports, table 0 "Cultivated area for major crops (ha)": 2020 report (2020 A/B), 2021 report (2021 A/B),
# 2022 report (2022 A/B), 2024 report (2023 A/B). Maize code 101 in the 2020+ list. 2024 A is NOT reproduced by the same
# formula (358k vs 249k published): the 2024 estimator differs (informational).
report += ["", "## D. Published cultivated maize area (ha) -- screening crop records x plot weight vs the annual reports", ""] + HDR
PUB_MAIZE = {"2020_A": 221_521, "2020_B": 72_918, "2021_A": 236_642, "2021_B": 80_570, "2022_A": 219_683, "2022_B": 81_339, "2023_A": 226_982, "2023_B": 93_927, "2024_A": 249_435, "2024_B": 92_944}
for w, pub in PUB_MAIZE.items():
    f = next((x for x in (P["inter"] / f"SAS_{w}_screening_crops_clean.dta", P["inter"] / f"SAS_{w}_screening_clean.dta") if x.exists()), None)
    if f is None: row("D", f"{w} screening file missing", 0, 1); continue
    s, _, _ = read_dta(f, usecols=["crop", "crop_area", "wt"])
    est = (s.loc[s["crop"] == 101, "wt"] * s.loc[s["crop"] == 101, "crop_area"]).sum()
    row("D", f"{w} maize cultivated area (ha) vs report {pub:,}" + (" [informational: 2024 estimator not reproduced]" if w.startswith("2024") else ""), est, None if w.startswith("2024") else pub, 0.001)

# ---------------------------------------------------------------- E. coverage, keys, crop dictionaries, coding compatibility
report += ["", "## E. Module coverage, record keys, crop dictionaries, cross-wave coding compatibility", ""] + HDR
for canon, want in (("fertilizers_pesticides", 7), ("agricultural_practice", 7), ("screening_crops", 7), ("screening_agroforestry", 4), ("screening_antierosion", 4)):
    i = align["files"].get(f"SAS_pooled_{canon}.dta")
    row("E", f"module {canon}: years covered (expected {want})", len({w[:4] for w in i["waves"]}) if i else 0, want)
for f, i in align["files"].items():
    if f.startswith("SAS_pooled_plotcrop"): continue
    row("E", f"{f.replace('SAS_pooled_', '').replace('.dta', '')}: waves appended (informational)", len(i["waves"]), None)
keycols = ["wave", "farm_type", "segment", "holder", "plot", "crop"]
dups = pc.duplicated(keycols, keep=False).groupby(pc["wave"]).sum()
row("E", "crop-production rows sharing (wave, farm_type, segment, holder, plot, crop) -- NOT a unique key (informational)", int(dups.sum()), None)
for w, n in dups[dups > 0].items(): row("E", f"  {w}: rows with a duplicated key (informational)", int(n), None)
thr = align.get("vl_threshold", 0.6); SENT = {98, 99, 998, 999, 9998, 9999}
MISSING_LIKE = {"not stated", "missing", "dont know", "dk", "unknown", "not known", "non determine", "nd", "ns", "not applicable", "na"}
_SYN = {"others": "other", "yego": "yes", "oya": "no", "specify": "", "please": "", "specified": ""}
def _norm2(s): return " ".join(w for w in (_SYN.get(x, x) for x in re.sub(r"[^a-z0-9]+", " ", str(s).lower()).split()) if w)
def _same(x, y):
    a, b = _norm2(x), _norm2(y)
    if a == b or (a in MISSING_LIKE and b in MISSING_LIKE): return True
    ta, tb = set(a.split()), set(b.split())
    if ta and tb and (ta <= tb or tb <= ta): return True
    return difflib.SequenceMatcher(None, a, b).ratio() >= thr
# crop dictionaries: within a crop list generation every code must carry the same text in every wave
def _norm(s): return " ".join(re.sub(r"[^a-z0-9]+", " ", str(s).lower()).split())
gen = lambda y: "2013" if y == "2013" else "2014-2016" if y in ("2014", "2015", "2016") else "2017-2019" if y in ("2017", "2018", "2019") else "2020+"
dicts = {}
for y, m in metas.items():
    for mk, i in m.items():
        d = i.get("value_labels", {}).get("crop", {})
        if len(d) >= 20:
            for k, v in d.items(): dicts.setdefault(gen(y), {}).setdefault(float(k), {}).setdefault(_norm(v), set()).add(f"{y} {mk}")
def _wordings(texts):
    """distinct meanings among label texts: spelling variants / '... specify' collapse (difflib >= 0.6 or token containment)"""
    kinds = []
    for x in texts:
        for k in kinds:
            if _same(x, k): break
        else: kinds.append(x)
    return kinds
conf = {g: {k: t for k, t in codes.items() if len(_wordings(list(t))) > 1} for g, codes in dicts.items()}
for g, codes in sorted(dicts.items()):
    row("E", f"crop list {g}: codes whose meaning changes between waves of the same list generation (informational; {len(codes)} codes; use crop_name)", len(conf[g]), None)
for g, c in conf.items():
    if c: report.append(f"  {g}: " + "; ".join(f"{k:g}: {' / '.join(sorted(t))}" for k, t in sorted(c.items())[:12]))
# pooled columns: re-derive value-label compatibility from the per-wave meta files
bad, nsplit, nsplit_vl = [], 0, 0
for fname, i in align["files"].items():
    wm = i.get("wave_modules", {})
    for base, d in i["decisions"].items():
        if base in ("crop", "stratum"): continue          # wave-specific codes by design: no pooled value labels (crop_list / crop_name; stratum per the cleaned files)
        if len(d["versions"]) > 1:
            nsplit += 1
            if any("value labels" in r or "unlabelled" in r for r in d.get("split_reasons", [])): nsplit_vl += 1
        for col, ws in d["versions"].items():
            labs = []
            for w in ws:
                y, mk = wm.get(w, (None, None))
                if y in metas and mk in metas[y]:
                    labs.append((w, {float(k): v for k, v in metas[y][mk].get("value_labels", {}).get(base, {}).items() if str(k).replace('.', '', 1).lstrip('-').isdigit()}))
            for a_i in range(len(labs)):
                for b_i in range(a_i + 1, len(labs)):
                    a, b = labs[a_i][1], labs[b_i][1]
                    for c in set(a) & set(b):
                        if c not in SENT and not _same(a[c], b[c]): bad.append((fname, col, labs[a_i][0], labs[b_i][0], c, a[c], b[c]))
row("E", "pooled columns holding waves with incompatible value-label texts for the same code (must be 0)", len({(b[0], b[1]) for b in bad}), 0)
row("E", "variables split into versions, all pooled files (informational)", nsplit, None)
row("E", "of which because of value labels or unlabelled ranges (informational)", nsplit_vl, None)
row("E", "variables with codes observed outside their own wave's value labels -- stale labels (informational)", sum(len(i.get("stale_labels", {})) for i in align["files"].values()), None)
if bad: report += ["", "Incompatible pairs: " + "; ".join(f"{f}:{c}: {y1}/{y2} code {k:g} {p!r} vs {q!r}" for f, c, y1, y2, k, p, q in bad[:20])]
report += ["", f"**{fails} check(s) failed.**" if fails else "**All checks passed.**"]
(LOGS / "checks_report.txt").write_text("\n".join(report)); log.info("\n" + "\n".join(report))
if fails: sys.exit(f"{fails} check(s) failed -- see logs/checks_report.txt")
log.info("03_checks done")
