"""
housing_table.py -- the housing regressions as LaTeX tables.

    python housing_table.py [main|lasso|both]

    output/tables/table_housing_main.tex     no controls
    output/tables/table_housing_lasso.tex    controls chosen by cluster-robust PDS lasso
    output/tables/table_housing_<spec>.csv   the same numbers, one row per cell

Each cell is

    coefficient (standard error) [p clustered] {p Conley}

  coefficient   treated, in standard deviations of the 2002 control distribution
  (se)          clustered at sector
  [p]           from that clustered standard error
  {p}           Conley spatial HAC, Bartlett kernel, 25 km cutoff on sector centroids. Clustering at
                sector is no adjustment at all in the single-wave regressions, where every cluster
                holds one observation, and treatment is organised around three parks rather than
                scattered at random. Conley lets neighbouring sectors share errors instead.

No multiplicity correction: premature while the outcome set is still moving. The Romano-Wolf
stepdown of List, Shaikh and Xu (2019) sits behind the MHT flag in housing_inference.py.

The tables need booktabs. \\usepackage{booktabs} in the preamble.
"""
import sys

import pandas as pd

sys.path.insert(0, str(__import__("pathlib").Path(__file__).resolve().parents[1] / "figures"))
import bar_chart_housing as B          # noqa: E402
import build_controls as CTL           # noqa: E402

OUT = B.DB / "output/tables"
ORDER = B.COMPONENTS + ["index"]
WAVES = [("2012", "2012"), ("2022", "2022"), ("pooled", "Pooled")]
PANEL = ["Bordering or Gates+", "Gates+"]
TITLE = {"main": "no controls beyond the 2002 level, park and district by wave fixed effects",
         "lasso": "controls chosen by cluster-robust post-double-selection lasso"}


def cell(r):
    if r is None or r.empty:
        return "\\multicolumn{1}{c}{--}"
    r = r.iloc[0]
    return (f"${r.b:+.3f}$ ({r.se_cluster:.3f}) [{r.p_cluster:.3f}] "
            f"$\\{{${r.p_conley25:.3f}$\\}}$")


def build(spec):
    d = pd.read_csv(CTL.ANALYSIS / "reg_housing_inference.csv")
    d = d[d.spec == spec]
    n = {t: int(d[d.treatment == t].n.iloc[0]) for t in PANEL if (d.treatment == t).any()}
    L = [
        "% generated by output/tables/housing_table.py -- do not edit by hand",
        "\\begin{table}[htbp]", "\\centering", "\\footnotesize",
        f"\\caption{{Housing outcomes by treatment definition: {TITLE[spec]}.}}",
        f"\\label{{tab:housing_{spec}}}",
        "\\begin{tabular}{l ccc}", "\\toprule",
        "Outcome & 2012 & 2022 & Pooled \\\\", "\\midrule",
    ]
    for k, tn in enumerate(PANEL):
        sub = d[d.treatment == tn]
        if sub.empty:
            continue
        letter = "AB"[k]
        treated = {"Bordering or Gates+": 44, "Gates+": 12}.get(tn, "")
        L.append(f"\\multicolumn{{4}}{{l}}{{\\textit{{Panel {letter}: {tn} "
                 f"({treated} treated sectors)}}}} \\\\[2pt]")
        for o in ORDER:
            nice = B.NICE.get(o, o)
            if o == "index":
                L.append("\\addlinespace")
                nice = f"\\textbf{{{nice}}}"
            cells = " & ".join(cell(sub[(sub.outcome == o) & (sub.wave == w)]) for w, _ in WAVES)
            L.append(f"{nice} & {cells} \\\\")
        L.append("\\midrule" if k == 0 else "\\bottomrule")
    ctrl = int(d.n.max() - 44) if len(d) else 328
    L += [
        "\\end{tabular}",
        "\\begin{minipage}{\\textwidth}\\vspace{4pt}\\scriptsize",
        "\\textit{Notes.} Each cell reports the coefficient on the treatment indicator from a "
        "separate regression of the outcome on treatment, the sector's own 2002 level of that "
        "outcome, park fixed effects and district fixed effects, run on 2012, on 2022, and on the "
        "two pooled with district by wave fixed effects. Estimated at sector level, unweighted, "
        "since treatment is assigned at sector level. Outcomes are expressed in standard deviations "
        "of the 2002 control distribution; the index averages the five components. "
        "Parentheses give standard errors clustered at sector, square brackets the p-value from "
        "them, and braces the p-value from Conley spatial HAC errors with a Bartlett kernel and a "
        "25 km cutoff on sector centroids. "
        f"The comparison group is the same {ctrl} sectors in both panels: those that neither border "
        "a long-standing national park nor sit within 5 km of a park entrance, less the City of "
        "Kigali and the four largest towns of 2002. "
        "\\textit{Source:} Rwanda Population and Housing Census 2002, 2012 and 2022, 10 per cent "
        "public-use samples.",
        "\\end{minipage}", "\\end{table}",
    ]
    return "\n".join(L), d


if __name__ == "__main__":
    which = sys.argv[1] if len(sys.argv) > 1 else "both"
    OUT.mkdir(parents=True, exist_ok=True)
    for spec in (["main", "lasso"] if which == "both" else [which]):
        tex, d = build(spec)
        (OUT / f"table_housing_{spec}.tex").write_text(tex + "\n")
        keep = ["treatment", "outcome", "wave", "b", "se_cluster", "p_cluster",
                "p_conley25", "p_conley50", "k_selected", "n"]
        d[[c for c in keep if c in d.columns]].to_csv(OUT / f"table_housing_{spec}.csv", index=False)
        print("written:", OUT / f"table_housing_{spec}.tex")
