"""
03_checks.py -- WBES: independent verification of 3_Final/WBES_pooled_establishment.dta -> logs/checks_report.txt

  A. Rows per round against the implementation reports, and against the per-round cleaned files.
  B. Python vs Stata 17 recomputed from the written .dta (skipped when Stata is absent).
  C. Weighted universe per round (the strict-eligibility weight) and the ordering of the three
     universes, which holds by construction of the eligibility assumptions (it does not hold firm by
     firm). 2006 and 2011 carry no weights in the World Bank's panel file.
  D. Keys and the panel link: the World Bank firm id is unique; a panel id never spans two rounds
     of the same year; the firms the panel marks as interviewed in several rounds do appear in those
     rounds; the 2019 rows carry the panel link.
  E. Cross-round coding compatibility: within every pooled column the rounds' value labels are
     re-derived from the per-round meta files, independently of 02_merge's own record.

Written against the native names: the file carries the clean names and is read back through
variable_names.csv, as in every dataset pipeline.
"""
import difflib, json, os, re, shutil, subprocess, sys
import numpy as np, pandas as pd
from wbes_helpers import paths, get_logger, read_dta, read_meta, LOGS, HERE, NameTable, DATASET_TAG

log = get_logger("03_checks"); P = paths()
NAMES = NameTable(HERE / "variable_names.csv", DATASET_TAG); POOLED = "pooled:WBES_pooled_establishment.dta"
CLEAN, NATIVE = NAMES.clean(POOLED), NAMES.native(POOLED)
WAVES = ["2006", "2011", "2019", "2023"]
PUBLISHED = {"2006": 212, "2011": 241, "2019": 360, "2023": 358}      # implementation reports
WEIGHTED = {"2019", "2023"}      # the World Bank panel file carries no sampling weights for 2006 / 2011
report = ["# WBES checks report", "", "Generated by 03_checks.py.", ""]; fails = 0
def row(section, name, ours, ref, tol=0.0):
    global fails
    ok = None if ref is None else abs(float(ours) - float(ref)) <= tol * max(1.0, abs(float(ref)))
    fails += (ok is False)
    report.append(f"| {section} | {name} | {ours:,.0f} | {'' if ref is None else f'{ref:,.0f}'} | {'PASS' if ok else ('n/a' if ok is None else '**FAIL**')} |")
HDR = ["| section | statistic | Python | reference | result |", "|---|---|---:|---:|---|"]

want = ["wave", "year", "idstd", "panelid", "panel", "wstrict", "wmedian", "wweak", "a4a", "a6a", "strata"]
cols = [CLEAN[c] for c in want if c in CLEAN and CLEAN[c] in read_meta(P["final"] / "WBES_pooled_establishment.dta").column_names]
est, _, _ = read_dta(P["final"] / "WBES_pooled_establishment.dta", usecols=cols)
est = est.rename(columns=NATIVE)
for c in ("wstrict", "wmedian", "wweak", "panelid", "idstd"):
    if c in est.columns: est[c] = pd.to_numeric(est[c], errors="coerce")

# ---- A
report += ["## A. Rows per round", ""] + HDR
al = json.load(open(LOGS / "merge_alignment.json")); DUP = al.get("duplicates_dropped", {}).get("WBES_pooled_establishment.dta", {})
row("A", "exact duplicate rows dropped before saving (Matteo's rule; informational)", sum(DUP.values()), None)
for w in WAVES:
    n = int((est["wave"] == w).sum())
    row("A", f"{w} establishments vs the implementation report ({PUBLISHED[w]:,})", n, PUBLISHED[w] - DUP.get(w, 0))
    f = P["inter"] / f"WBES_{w}_establishment_clean.dta"
    if f.exists(): row("A", f"{w} rows == the cleaned round file", n, read_meta(f).number_rows - DUP.get(w, 0))
row("A", "pooled rows == the four rounds together", len(est), sum(PUBLISHED.values()) - sum(DUP.values()))

# ---- B
report += ["", "## B. Stata 17 recomputation from the written .dta", ""]
stata = "/Applications/Stata/StataMP.app/Contents/MacOS/stata-mp"
if not os.path.exists(stata): stata = shutil.which("stata-mp") or shutil.which("stata")
if stata:
    use = [CLEAN[c] for c in ("wave", "wstrict")]
    do, out = HERE / "stata_checks.do", LOGS / "stata_checks.csv"
    do.write_text(f'''* stata_checks.do -- recompute the WBES check statistics in Stata (written by 03_checks.py)
clear all
set more off
use {" ".join(use)} using "{P["final"] / "WBES_pooled_establishment.dta"}", clear
rename ({" ".join(use)}) (wave wstrict)
gen long one = 1
collapse (sum) n=one sum_w=wstrict, by(wave)
export delimited using "{out}", replace
''')
    r = subprocess.run([stata, "-q", "-b", "do", str(do)], cwd=str(HERE), capture_output=True, text=True)
    logf = HERE / "stata_checks.log"
    if out.exists():
        st = pd.read_csv(out).set_index("wave"); report += HDR
        for w in WAVES:
            g = est[est["wave"] == w]
            row("B", f"{w} rows", len(g), st.loc[int(w) if st.index.dtype != object else w, "n"])
            row("B", f"{w} weighted universe (strict)", g["wstrict"].sum(), st.loc[int(w) if st.index.dtype != object else w, "sum_w"], 1e-9)
        if logf.exists(): (LOGS / "stata_checks.log").write_text(logf.read_text()); logf.unlink()
    else:
        report.append(f"Stata run produced no output (rc={r.returncode}); see {logf}"); fails += 1
else:
    report.append("Stata not found on this machine -- section B skipped."); log.warning("Stata not found; skipping B")

# ---- C
# The three weights are three assumptions about how many of the frame's establishments were eligible, so the
# UNIVERSES are ordered (strict <= median <= weak) while a single firm's three weights need not be: they come from
# different response-rate denominators. The World Bank's panel file ships no weights at all for 2006 and 2011.
report += ["", "## C. Weights", ""] + HDR
for w in WAVES:
    g = est[est["wave"] == w]
    if w not in WEIGHTED:
        row("C", f"{w} rows with a sampling weight (the panel file ships none for this round)", int(g["wstrict"].notna().sum()), 0)
        continue
    row("C", f"{w} weighted universe of eligible establishments (strict; informational)", g["wstrict"].sum(), None)
    if {"wmedian", "wweak"} <= set(g.columns):
        tot = [g[c].sum() for c in ("wstrict", "wmedian", "wweak")]
        row("C", f"{w} universes out of order strict <= median <= weak (must be 0)", int(tot[0] > tot[1] + 1e-6) + int(tot[1] > tot[2] + 1e-6), 0)
        row("C", f"{w} establishments whose own strict weight exceeds its median weight (informational)", int((g["wstrict"] > g["wmedian"] + 1e-9).sum()), None)
    row("C", f"{w} rows with a missing strict weight (must be 0)", int(g["wstrict"].isna().sum()), 0)
    row("C", f"{w} rows with a strict weight of zero or less (must be 0)", int((g["wstrict"] <= 0).sum()), 0)

# ---- D
report += ["", "## D. Keys and the panel link", ""] + HDR
row("D", "World Bank firm id unique over the pooled file", est["idstd"].nunique(), len(est))
if "panelid" in est.columns:
    linked = est[est["panelid"].notna()]
    row("D", "rows carrying a panel id (2006-2019; 2023 is outside the panel; informational)", len(linked), None)
    dup = int(linked.groupby(["panelid", "wave"]).size().gt(1).sum())
    row("D", "panel ids appearing twice within one round (must be 0)", dup, 0)
    n_multi = int((linked.groupby("panelid")["wave"].nunique() > 1).sum())
    row("D", "firms interviewed in more than one round (informational)", n_multi, None)
    row("D", "2019 rows carrying the panel link", int(linked[linked["wave"] == "2019"].shape[0]), PUBLISHED["2019"])
    row("D", "2023 rows carrying a panel id (must be 0: 2023 is not in the World Bank panel)", int(est.loc[est["wave"] == "2023", "panelid"].notna().sum()), 0)

# ---- E
report += ["", "## E. Cross-round coding compatibility within pooled columns", ""] + HDR
metas = {w: json.load(open(LOGS / f"clean_{w}_meta.json")) for w in WAVES if (LOGS / f"clean_{w}_meta.json").exists()}
thr = al.get("vl_threshold", 0.6)
SENT = {98, 99, 998, 999, 9998, 9999, -9, -8, -7, -6, -5, -4}       # WBES: negative codes are don't know / refusal / not applicable
MISSING_LIKE = {"dont know", "do not know", "don't know", "refusal", "does not apply", "not applicable", "na", "missing", "spontaneous"}
def _norm(s): return " ".join(w for w in re.sub(r"[^a-z0-9]+", " ", str(s).lower()).split() if w)
def _same(x, y):
    a, b = _norm(x), _norm(y)
    if a == b or (a in MISSING_LIKE and b in MISSING_LIKE): return True
    ta, tb = set(a.split()), set(b.split())
    if ta and tb and (ta <= tb or tb <= ta): return True
    return difflib.SequenceMatcher(None, a, b).ratio() >= thr
bad, n_split_vl = [], 0
for base, d in al["decisions"].items():
    if len(d["versions"]) > 1 and any("value labels" in r or "unlabelled" in r for r in d.get("split_reasons", [])): n_split_vl += 1
    for col, ws in d["versions"].items():
        labs = [(w, {float(k): v for k, v in metas[w]["value_labels"].get(base, {}).items() if str(k).replace(".", "", 1).lstrip("-").isdigit()}) for w in ws if w in metas]
        for i in range(len(labs)):
            for j in range(i + 1, len(labs)):
                a2, b2 = labs[i][1], labs[j][1]
                for c in set(a2) & set(b2):
                    if c not in SENT and not _same(a2[c], b2[c]): bad.append((col, labs[i][0], labs[j][0], c, a2[c], b2[c]))
row("E", "pooled columns holding rounds with incompatible value-label texts for the same code (must be 0)", len({b[0] for b in bad}), 0)
row("E", "variables split into versions because of value labels or unlabelled ranges (informational)", n_split_vl, None)
row("E", "variables with codes observed outside their own round's value labels (informational)", len(al.get("stale_labels", {})), None)
row("E", "columns in the pooled file (informational)", len(al["establishment"]["vars"]), None)
if bad: report += ["", "Incompatible pairs: " + "; ".join(f"{c}: {w1}/{w2} code {k:g} {p!r} vs {q!r}" for c, w1, w2, k, p, q in bad[:20])]

report += ["", f"**{fails} check(s) failed.**" if fails else "**All checks passed.**"]
(LOGS / "checks_report.txt").write_text("\n".join(report)); log.info("\n" + "\n".join(report))
if fails: sys.exit(f"{fails} check(s) failed -- see logs/checks_report.txt")
log.info("03_checks done")
