"""
03_checks.py -- EICV: independent verification of 3_Final/ outputs -> logs/checks_report.md

  A. Python pooled person file vs the OLD Stata pipeline's outputs (EICV3-7; logs/benchmark_old_stata.json)
  B. Python vs Stata 17 recomputation on the written files (skipped if Stata is absent)
  C. Weighted poverty headcounts (household file, NISR's own poverty flags x pop_wt) vs NISR's published rates
  D. Household/person consistency (sum of hhsize == person rows; one row per household)
"""
import json, os, shutil, subprocess, sys
import numpy as np, pandas as pd
from eicv_helpers import paths, get_logger, read_dta, read_meta, LOGS, HERE

log = get_logger("03_checks"); P = paths()
report = ["# EICV checks report", "", "Generated by 03_checks.py.", ""]; fails = 0
def row(section, name, ours, ref, tol=0.0, fmt="{:,.0f}"):
    global fails
    ok = None if ref is None else abs(float(ours) - float(ref)) <= tol * max(1.0, abs(float(ref)))
    fails += (ok is False)
    report.append(f"| {section} | {name} | {fmt.format(ours)} | {'' if ref is None else fmt.format(ref)} | {'PASS' if ok else ('n/a' if ok is None else '**FAIL**')} |")

def cols_of(fname, wanted):
    names = read_meta(P["final"] / fname).column_names
    return [c for c in wanted if c in names]

person, _, _ = read_dta(P["final"] / "EICV_pooled_person.dta", usecols=cols_of("EICV_pooled_person.dta", ["wave", "wt", "sex", "dist", "hhid"]))
_hh_names = read_meta(P["final"] / "EICV_pooled_household.dta").column_names
hh_cols = cols_of("EICV_pooled_household.dta", ["wave", "wt", "hhsize", "hhid", "pop_wt"]) + [c for c in _hh_names if c.startswith(("poverty", "pov"))]
hh, _, _ = read_dta(P["final"] / "EICV_pooled_household.dta", usecols=hh_cols)
ours = {w: {"n": len(g), "sum_wt": g["wt"].sum(), "n_hh": g["hhid"].nunique(), "n_dist": g["dist"].nunique(),
            "male": int((g["sex"] == 1).sum()), "female": int((g["sex"] == 2).sum())} for w, g in person.groupby("wave", sort=False)}

report += ["## A. Python pooled person file vs old Stata outputs (3 Jul 2026; EICV1/2 were not processed then)", "",
           "| section | statistic | Python | reference | result |", "|---|---|---:|---:|---|"]
bench = json.load(open(LOGS / "benchmark_old_stata.json"))
old = next(f for f in bench["files"] if f["file"].startswith("EICV_pooled"))["by_round"]
for w in ["EICV3", "EICV4_CS", "EICV5_CS", "EICV7_CS"]:
    o, b = ours[w], old[w]
    row("A", f"{w} person rows", o["n"], b["n"]); row("A", f"{w} sum wt (persons)", o["sum_wt"], b["sum_wt"], 1e-9); row("A", f"{w} households", o["n_hh"], b["n_hh"])
    row("A", f"{w} male", o["male"], b["sex_counts"].get("1")); row("A", f"{w} female", o["female"], b["sex_counts"].get("2"))

report += ["", "## B. Stata 17 recomputation from the written .dta files", ""]
stata = "/Applications/Stata/StataMP.app/Contents/MacOS/stata-mp"
if not os.path.exists(stata): stata = shutil.which("stata-mp") or shutil.which("stata")
if stata:
    do, out, outh = HERE / "stata_checks.do", LOGS / "stata_checks.csv", LOGS / "stata_checks_hh.csv"
    do.write_text(f'''* stata_checks.do -- recompute EICV check statistics in Stata (written by 03_checks.py)
clear all
set more off
use wave wt sex dist hhid using "{P["final"] / "EICV_pooled_person.dta"}", clear
gen byte male = sex == 1
gen byte female = sex == 2
gen long one = 1
bysort wave hhid: gen byte first_hh = _n == 1
collapse (sum) n=one sum_wt=wt male female n_hh=first_hh, by(wave)
export delimited using "{out}", replace
use wave wt hhsize hhid using "{P["final"] / "EICV_pooled_household.dta"}", clear
collapse (count) n_hh=hhid (sum) hhsize_sum=hhsize sum_wt_hh=wt, by(wave)
export delimited using "{outh}", replace
''')
    r = subprocess.run([stata, "-q", "-b", "do", str(do)], cwd=str(HERE), capture_output=True, text=True)
    logf = HERE / "stata_checks.log"
    if out.exists() and outh.exists():
        st, sth = pd.read_csv(out).set_index("wave"), pd.read_csv(outh).set_index("wave")
        report += ["| section | statistic | Python | Stata | result |", "|---|---|---:|---:|---|"]
        for w in ours:
            o, s = ours[w], st.loc[w]
            row("B", f"{w} person rows", o["n"], s["n"]); row("B", f"{w} sum wt", o["sum_wt"], s["sum_wt"], 1e-9)
            row("B", f"{w} male", o["male"], s["male"]); row("B", f"{w} female", o["female"], s["female"]); row("B", f"{w} households (person file)", o["n_hh"], s["n_hh"])
        for w, g in hh.groupby("wave", sort=False):
            row("B", f"{w} households (household file)", len(g), sth.loc[w, "n_hh"]); row("B", f"{w} sum hhsize", g["hhsize"].sum(), sth.loc[w, "hhsize_sum"])
            row("B", f"{w} sum household weight", g["wt"].sum(), sth.loc[w, "sum_wt_hh"], 1e-9)
        if logf.exists(): (LOGS / "stata_checks.log").write_text(logf.read_text()); logf.unlink()
    else:
        report.append(f"Stata run produced no output (rc={r.returncode}); see {logf}"); fails += 1
else:
    report.append("Stata not found on this machine -- section B skipped."); log.warning("Stata not found; skipping B")

# ---- C. published poverty headcounts. NISR poverty flags are coded 0 / 100 (percent) in the poverty
#      files; the person-weighted rate uses pop_wt (household weight x household size).
# NISR poverty headcounts. EICV3 = 46.0: the shipped EICV3 poverty file is NISR's January-2014-price
# re-expression (built for the EICV3-EICV4 comparison; the original 2010/11 basis gave 44.9). EICV7 is on
# the revised 2024 basis (27.4).
PUB_POV = {"EICV3": 46.0, "EICV4_CS": 39.1, "EICV5_CS": 38.2, "EICV7_CS": 27.4}
POVVAR = {"EICV3": "poverty", "EICV4_CS": "pov", "EICV5_CS": "pov_jan", "EICV7_CS": "pov_jan"}
report += ["", "## C. Weighted poverty headcount (%) vs NISR published rates", "", "| section | statistic | Python | published | result |", "|---|---|---:|---:|---|"]
# sample sizes stated in the documentation (z_Documentation): EICV1 6,450 households allocated (Megill 2004, table 6; 6,420 interviewed),
# EICV2 6,900 (Muñoz 2004), EICV4 14,419 and EICV5 14,580 (EICV5 VUP thematic report), EICV7 15,054 households / 62,110 persons (DDI)
PUB_HH = {"EICV1": (6_450, 0.01), "EICV2": (6_900, 0), "EICV4_CS": (14_419, 0), "EICV5_CS": (14_580, 0), "EICV7_CS": (15_054, 0)}
for w, (n, tol) in PUB_HH.items():
    if w in set(hh["wave"]): row("C", f"{w} households interviewed (documentation)", int((hh["wave"] == w).sum()), n, tol)
if "EICV7_CS" in set(person["wave"]): row("C", "EICV7_CS person rows (DDI: 62,110)", int((person["wave"] == "EICV7_CS").sum()), 62_110)
for w, pub in PUB_POV.items():
    g = hh[hh.wave == w]
    cands = [c for c in g.columns if c.startswith(POVVAR[w])]        # the flag may carry a version or module suffix
    var = next((c for c in cands if g[c].notna().any() and set(g[c].dropna().unique()) <= {0, 100}), None)
    if var is None: report.append(f"| C | {w} poverty variable {POVVAR[w]} not found in 0/100 coding | | | n/a |"); continue
    wgt = g["pop_wt"] if "pop_wt" in g and g["pop_wt"].notna().all() else g["wt"] * g["hhsize"]
    rate = 100 * (wgt * (g[var] == 100)).sum() / wgt.sum()
    row("C", f"{w} poverty headcount ({var}, pop_wt-weighted)", rate, pub, 0.01, fmt="{:.2f}")

report += ["", "## D. Household / person consistency", "", "| section | statistic | Python | reference | result |", "|---|---|---:|---:|---|"]
for w, g in hh.groupby("wave", sort=False):
    p = person[person.wave == w]
    row("D", f"{w} sum hhsize == person rows", g["hhsize"].sum(), len(p)); row("D", f"{w} households == distinct hhid in person file", len(g), p["hhid"].nunique())
    row("D", f"{w} household rows unique", g["hhid"].nunique(), len(g))
report += ["", f"**{fails} check(s) failed.**" if fails else "**All checks passed.**"]
(LOGS / "checks_report.md").write_text("\n".join(report)); log.info("\n" + "\n".join(report))
if fails: sys.exit(f"{fails} check(s) failed -- see logs/checks_report.md")
log.info("03_checks done")
