"""
03_checks.py -- LFS: independent verification of 3_Final/ outputs.

Five sections, each row PASS/FAIL (or informational), written to logs/checks_report.txt:
  A. Python pooled file vs the OLD Stata pipeline's outputs (logs/benchmark_old_stata.json):
     rows, sum of annual weight, weighted working-age population, sex counts, by year.
  B. Python vs Stata: the same statistics recomputed by Stata 17 from the .dta files we wrote
     (stata_checks.do is regenerated here with the current paths; skipped if Stata is absent).
  C. Weighted working-age population vs the figures published in NISR's annual LFS reports.
  D. Household file: hhsize = roster count, household-interviews unique, exactly one head per
     household-interview (exceptions counted), weight constant within the household-interview.
  E. Cross-year coding compatibility: within every pooled column the years' value labels are
     compatible (re-derived from the per-year meta files, independently of 02_merge's record);
     informational counts of value-label splits and of stale labels.
"""
import json, os, shutil, subprocess, sys
import numpy as np, pandas as pd
from lfs_helpers import paths, get_logger, read_dta, LOGS, HERE

log = get_logger("03_checks")
P = paths()
report = ["# LFS checks report", "", f"Generated by 03_checks.py.", ""]
fails = 0
def row(section, name, ours, ref, tol=0.0):
    global fails
    ok = (abs(float(ours) - float(ref)) <= tol * max(1.0, abs(float(ref)))) if ref is not None else None
    fails += (ok is False)
    report.append(f"| {section} | {name} | {ours:,.0f} | {ref if ref is None else f'{ref:,.0f}'} | {'PASS' if ok else ('n/a' if ok is None else '**FAIL**')} |")

from lfs_helpers import read_meta
pcols = read_meta(P["final"] / "LFS_pooled_person.dta").column_names
a02cols = [c for c in pcols if c == "a02" or c.startswith("a02_v")]
person, _, _ = read_dta(P["final"] / "LFS_pooled_person.dta", usecols=["year", "wt", "wap16", "sex", "dist", "hhid", "interview"] + a02cols)
hh, _, _ = read_dta(P["final"] / "LFS_pooled_household.dta", usecols=["year", "wt", "hhsize", "hhid", "interview", "head_sex"])
person["is_head"] = 0
for c in a02cols: person["is_head"] = person["is_head"] | (pd.to_numeric(person[c], errors="coerce") == 1).astype(int)
ours = {}
for y, g in person.groupby("year"):
    ours[int(y)] = {"n": len(g), "sum_wt": g["wt"].sum(), "wpop_wap16": (g["wap16"] * g["wt"]).sum(),
                    "n_dist": g["dist"].nunique(), "male": int((g["sex"] == 1).sum()), "female": int((g["sex"] == 2).sum())}

# ---- A. vs old Stata outputs
report += ["## A. Python pooled file vs old Stata outputs (3 Jul 2026)", "", "| section | statistic | Python | reference | result |", "|---|---|---:|---:|---|"]
bench = json.load(open(LOGS / "benchmark_old_stata.json"))
old = next(f for f in bench["files"] if f["file"].startswith("LFS_panel"))["by_year"]
_al = json.load(open(LOGS / "merge_alignment.json")); DUP = _al.get("duplicates_dropped", {}).get("LFS_pooled_person.dta", {}); DUPW = _al.get("wt_dropped", {}).get("LFS_pooled_person.dta", {})
row("A", "exact duplicate rows dropped before saving the pooled file (Matteo's rule; informational)", sum(DUP.values()), None)
for y in sorted(ours):
    o, b = ours[y], old.get(str(y), {}); dr, dw = DUP.get(str(y), 0), DUPW.get(str(y), 0.0)
    row("A", f"{y} rows" + (f" (+{dr} exact duplicates dropped)" if dr else ""), o["n"], None if b.get("n") is None else b["n"] - dr)
    row("A", f"{y} sum wt", o["sum_wt"], None if b.get("sum_wt_annual") is None else b["sum_wt_annual"] - dw, 1e-9)
    # the old Stata outputs still contain the exact duplicates: where rows were dropped, the sex counts and the weighted 16+ population are informational (the published WAP test in section C is the hard check)
    row("A", f"{y} weighted 16+ pop" + (" (old outputs include the duplicates; informational)" if dr else ""), o["wpop_wap16"], None if dr else b.get("wpop_wap16"), 1e-9)
    row("A", f"{y} districts", o["n_dist"], b.get("n_dist"))
    row("A", f"{y} male" + (" (informational, see above)" if dr else ""), o["male"], None if dr else (b.get("A01_counts") or {}).get("1"))
    row("A", f"{y} female" + (" (informational, see above)" if dr else ""), o["female"], None if dr else (b.get("A01_counts") or {}).get("2"))

# ---- B. Stata recomputation
report += ["", "## B. Stata 17 recomputation from the written .dta files", ""]
stata = "/Applications/Stata/StataMP.app/Contents/MacOS/stata-mp"
if not os.path.exists(stata): stata = shutil.which("stata-mp") or shutil.which("stata")
if stata:
    do = HERE / "stata_checks.do"; out = LOGS / "stata_checks.csv"
    do.write_text(f'''* stata_checks.do -- recompute LFS check statistics in Stata (written by 03_checks.py)
clear all
set more off
use "{P["final"] / "LFS_pooled_person.dta"}", clear
gen double wwap = wap16 * wt
gen byte male = sex == 1
gen byte female = sex == 2
gen long one = 1
collapse (sum) n=one sum_wt=wt wpop_wap16=wwap male female, by(year)
export delimited using "{out}", replace
use "{P["final"] / "LFS_pooled_household.dta"}", clear
collapse (count) n_hh=hhid (sum) hhsize_sum=hhsize, by(year)
export delimited using "{LOGS / "stata_checks_hh.csv"}", replace
''')
    r = subprocess.run([stata, "-q", "-b", "do", str(do)], cwd=str(HERE), capture_output=True, text=True)
    logf = HERE / "stata_checks.log"
    if out.exists():
        st = pd.read_csv(out).set_index("year")
        report += ["| section | statistic | Python | Stata | result |", "|---|---|---:|---:|---|"]
        for y in sorted(ours):
            o = ours[y]; s = st.loc[y]
            row("B", f"{y} rows", o["n"], s["n"]); row("B", f"{y} sum wt", o["sum_wt"], s["sum_wt"], 1e-9)
            row("B", f"{y} weighted 16+ pop", o["wpop_wap16"], s["wpop_wap16"], 1e-9)
            row("B", f"{y} male", o["male"], s["male"]); row("B", f"{y} female", o["female"], s["female"])
        sth = pd.read_csv(LOGS / "stata_checks_hh.csv").set_index("year")
        for y, g in hh.groupby("year"):
            row("B", f"{y} household-interviews", len(g), sth.loc[int(y), "n_hh"])
            row("B", f"{y} sum hhsize", g["hhsize"].sum(), sth.loc[int(y), "hhsize_sum"])
        if logf.exists(): (LOGS / "stata_checks.log").write_text(logf.read_text()); logf.unlink()
    else:
        report.append(f"Stata run produced no output (rc={r.returncode}); see {logf}"); fails += 1
else:
    report.append("Stata not found on this machine -- section B skipped."); log.warning("Stata not found; skipping B")

# ---- C. published figures
# Working-age (16+) population as published in NISR annual LFS reports (zz_Reports/). Only the
# figures verified against the PDFs are listed; a missing entry means "not yet checked".
PUBLISHED_WAP16 = {   # zz_Reports/, working-age population (16+) as printed; 2017 has round reports only, 2023 no annual report
    2018: 6_966_096,   # LFS_2018_report.pdf
    2019: 7_231_536,   # LFS_2019_annual_report_1.pdf
    2020: 7_472_601,   # LFS_2020_labour_force_survey_annual_report.pdf
    2021: 7_718_871,   # LFS_2021_annual_report.pdf
    2022: 7_963_586,   # LFS_2022_annual_report.pdf, p. 1 and table 1.1
    2024: 8_303_568,   # LFS 2024 annual report, key indicators table
    2025: 8_541_210,   # LFS_2025_annual_report.pdf
}
report += ["", "## C. Weighted working-age population vs published NISR figures", "",
           "| section | statistic | Python | published | result |", "|---|---|---:|---:|---|"]
for y, v in PUBLISHED_WAP16.items(): row("C", f"{y} weighted 16+ pop", ours[y]["wpop_wap16"], v, 0.005)

# ---- household sanity
report += ["", "## D. Household file sanity", "", "| section | statistic | Python | reference | result |", "|---|---|---:|---:|---|"]
for y, g in hh.groupby("year"):
    p = person[(person.year == y) & person.hhid.notna()]
    row("D", f"{y} sum hhsize == person rows with hh key", g["hhsize"].sum(), len(p))
    row("D", f"{y} household-interviews", len(g), p.drop_duplicates(["hhid", "interview"]).shape[0])
    heads = p.groupby(["hhid", "interview"])["is_head"].sum()
    row("D", f"{y} household-interviews with exactly one head (0 heads: {int((heads == 0).sum())}, 2+: {int((heads > 1).sum())}; threshold 99.9%)", heads.eq(1).mean() * 100, 100, 0.001)
    row("D", f"{y} household-interviews with head_sex missing", int(g["head_sex"].isna().sum()), int((heads == 0).sum()))
    row("D", f"{y} wt constant within household-interview (% of household-interviews)", (p.groupby(["hhid", "interview"])["wt"].nunique() <= 1).mean() * 100, 100)

# ---- E. cross-year coding compatibility (independent re-derivation from the per-year meta files)
import difflib, re as _re
align = json.load(open(LOGS / "merge_alignment.json")); thr = align.get("vl_threshold", 0.6)
metas = {y: json.load(open(LOGS / f"clean_{y}_meta.json")) for y in range(2017, 2026) if (LOGS / f"clean_{y}_meta.json").exists()}
SENT = {98, 99, 998, 999, 9998, 9999}
MISSING_LIKE = {"not stated", "missing", "dont know", "dk", "unknown", "not known", "non determine", "nd", "ns", "not applicable", "na"}
_SYN = {"others": "other", "yego": "yes", "oya": "no", "specify": "", "please": "", "specified": ""}
def _norm(s): return " ".join(w for w in (_SYN.get(x, x) for x in _re.sub(r"[^a-z0-9]+", " ", str(s).lower()).split()) if w)
def _same(x, y):
    a, b = _norm(x), _norm(y)
    if a == b or (a in MISSING_LIKE and b in MISSING_LIKE): return True
    ta, tb = set(a.split()), set(b.split())
    if ta and tb and (ta <= tb or tb <= ta): return True
    return difflib.SequenceMatcher(None, a, b).ratio() >= thr
forced = set(align.get("force_align", []))
bad, forced_diff, ncols_split_vl = [], [], 0
for base, d in align["decisions"].items():
    if len(d["versions"]) > 1 and any("value labels" in r or "unlabelled" in r for r in d.get("split_reasons", [])): ncols_split_vl += 1
    for col, ys in d["versions"].items():
        labs = [(y, metas[y]["value_labels"].get(base) or {}) for y in ys if y in metas]
        for i in range(len(labs)):
            for j in range(i + 1, len(labs)):
                a, b = labs[i][1], labs[j][1]
                for c in set(a) & set(b):
                    if c not in SENT and not _same(a[c], b[c]):
                        bad.append((col, labs[i][0], labs[j][0], c, a[c], b[c]))
report += ["", "## E. Cross-year coding compatibility within pooled columns", "", "| section | statistic | Python | reference | result |", "|---|---|---:|---:|---|"]
row("E", "pooled columns holding years with incompatible value-label texts for the same code, must be 0", len({b[0] for b in bad}), 0)
row("E", "FORCE_ALIGN columns whose value-label wording differs across years (owner's judgement that the question is the same; informational)", len({b[0] for b in forced_diff}), None)
row("E", "variables split into versions because of value labels or unlabelled ranges (informational)", ncols_split_vl, None)
row("E", "variables with codes observed outside their own year's value labels -- stale labels (informational; listed in merge_alignment.json)", len(align.get("stale_labels", {})), None)
row("E", "forced splits (FORCE_SPLIT entries)", len(align.get("force_split", {})), None)
if bad: report += ["", "Incompatible pairs: " + "; ".join(f"{c}: {y1}/{y2} code {k} {p!r} vs {q!r}" for c, y1, y2, k, p, q in bad[:20])]
if forced_diff: report += ["", "FORCE_ALIGN wording differences: " + "; ".join(sorted({f"{c}: code {k} {p!r} vs {q!r}" for c, y1, y2, k, p, q in forced_diff})[:10])]

report += ["", f"**{fails} check(s) failed.**" if fails else "**All checks passed.**"]
(LOGS / "checks_report.txt").write_text("\n".join(report))
log.info("\n" + "\n".join(report))
if fails: sys.exit(f"{fails} check(s) failed -- see logs/checks_report.txt")
log.info("03_checks done")
