"""
03_checks.py -- LFS: independent verification of 3_Final/ outputs.

Three comparisons, each PASS/FAIL, written to logs/checks_report.txt:
  A. Python pooled file vs the OLD Stata pipeline's outputs (logs/benchmark_old_stata.json):
     rows, sum of annual weight, weighted working-age population, sex counts, by year.
  B. Python vs Stata: the same statistics recomputed by Stata 17 from the .dta files we wrote
     (stata_checks.do; skipped with a warning if Stata is not installed).
  C. Weighted totals vs figures published in NISR's annual LFS reports (hard-coded with source).
"""
import json, os, shutil, subprocess, sys
import numpy as np, pandas as pd
from lfs_helpers import paths, get_logger, read_dta, LOGS, HERE

log = get_logger("03_checks")
P = paths()
report = ["# LFS checks report", "", f"Generated by 03_checks.py.", ""]
fails = 0
def row(section, name, ours, ref, tol=0.0):
    global fails
    ok = (abs(float(ours) - float(ref)) <= tol * max(1.0, abs(float(ref)))) if ref is not None else None
    fails += (ok is False)
    report.append(f"| {section} | {name} | {ours:,.0f} | {ref if ref is None else f'{ref:,.0f}'} | {'PASS' if ok else ('n/a' if ok is None else '**FAIL**')} |")

person, _, _ = read_dta(P["final"] / "LFS_pooled_person.dta", usecols=["year", "wt", "wap16", "sex", "dist", "hhid", "interview"])
hh, _, _ = read_dta(P["final"] / "LFS_pooled_household.dta", usecols=["year", "wt", "hhsize", "hhid", "interview"])
ours = {}
for y, g in person.groupby("year"):
    ours[int(y)] = {"n": len(g), "sum_wt": g["wt"].sum(), "wpop_wap16": (g["wap16"] * g["wt"]).sum(),
                    "n_dist": g["dist"].nunique(), "male": int((g["sex"] == 1).sum()), "female": int((g["sex"] == 2).sum())}

# ---- A. vs old Stata outputs
report += ["## A. Python pooled file vs old Stata outputs (3 Jul 2026)", "", "| section | statistic | Python | reference | result |", "|---|---|---:|---:|---|"]
bench = json.load(open(LOGS / "benchmark_old_stata.json"))
old = next(f for f in bench["files"] if f["file"].startswith("LFS_panel"))["by_year"]
for y in sorted(ours):
    o, b = ours[y], old.get(str(y), {})
    row("A", f"{y} rows", o["n"], b.get("n"))
    row("A", f"{y} sum wt", o["sum_wt"], b.get("sum_wt_annual"), 1e-9)
    row("A", f"{y} weighted 16+ pop", o["wpop_wap16"], b.get("wpop_wap16"), 1e-9)
    row("A", f"{y} districts", o["n_dist"], b.get("n_dist"))
    row("A", f"{y} male", o["male"], (b.get("A01_counts") or {}).get("1"))
    row("A", f"{y} female", o["female"], (b.get("A01_counts") or {}).get("2"))

# ---- B. Stata recomputation
report += ["", "## B. Stata 17 recomputation from the written .dta files", ""]
stata = "/Applications/Stata/StataMP.app/Contents/MacOS/stata-mp"
if not os.path.exists(stata): stata = shutil.which("stata-mp") or shutil.which("stata")
if stata:
    do = HERE / "stata_checks.do"; out = LOGS / "stata_checks.csv"
    do.write_text(f'''* stata_checks.do -- recompute LFS check statistics in Stata (written by 03_checks.py)
clear all
set more off
use "{P["final"] / "LFS_pooled_person.dta"}", clear
gen double wwap = wap16 * wt
gen byte male = sex == 1
gen byte female = sex == 2
gen long one = 1
collapse (sum) n=one sum_wt=wt wpop_wap16=wwap male female, by(year)
export delimited using "{out}", replace
use "{P["final"] / "LFS_pooled_household.dta"}", clear
collapse (count) n_hh=hhid (sum) hhsize_sum=hhsize, by(year)
export delimited using "{LOGS / "stata_checks_hh.csv"}", replace
''')
    r = subprocess.run([stata, "-q", "-b", "do", str(do)], cwd=str(HERE), capture_output=True, text=True)
    logf = HERE / "stata_checks.log"
    if out.exists():
        st = pd.read_csv(out).set_index("year")
        report += ["| section | statistic | Python | Stata | result |", "|---|---|---:|---:|---|"]
        for y in sorted(ours):
            o = ours[y]; s = st.loc[y]
            row("B", f"{y} rows", o["n"], s["n"]); row("B", f"{y} sum wt", o["sum_wt"], s["sum_wt"], 1e-9)
            row("B", f"{y} weighted 16+ pop", o["wpop_wap16"], s["wpop_wap16"], 1e-9)
            row("B", f"{y} male", o["male"], s["male"]); row("B", f"{y} female", o["female"], s["female"])
        sth = pd.read_csv(LOGS / "stata_checks_hh.csv").set_index("year")
        for y, g in hh.groupby("year"):
            row("B", f"{y} household-interviews", len(g), sth.loc[int(y), "n_hh"])
            row("B", f"{y} sum hhsize", g["hhsize"].sum(), sth.loc[int(y), "hhsize_sum"])
        if logf.exists(): (LOGS / "stata_checks.log").write_text(logf.read_text()); logf.unlink()
    else:
        report.append(f"Stata run produced no output (rc={r.returncode}); see {logf}"); fails += 1
else:
    report.append("Stata not found on this machine -- section B skipped."); log.warning("Stata not found; skipping B")

# ---- C. published figures
# Working-age (16+) population as published in NISR annual LFS reports (zz_Reports/). Only the
# figures verified against the PDFs are listed; a missing entry means "not yet checked".
PUBLISHED_WAP16 = {2024: 8_303_568}   # LFS 2024 annual report, key indicators table; matches the file exactly
report += ["", "## C. Weighted working-age population vs published NISR figures", "",
           "| section | statistic | Python | published | result |", "|---|---|---:|---:|---|"]
for y, v in PUBLISHED_WAP16.items(): row("C", f"{y} weighted 16+ pop", ours[y]["wpop_wap16"], v, 0.005)

# ---- household sanity
report += ["", "## D. Household file sanity", "", "| section | statistic | Python | reference | result |", "|---|---|---:|---:|---|"]
for y, g in hh.groupby("year"):
    p = person[(person.year == y) & person.hhid.notna()]
    row("D", f"{y} sum hhsize == person rows with hh key", g["hhsize"].sum(), len(p))
    row("D", f"{y} household-interviews", len(g), p.drop_duplicates(["hhid", "interview"]).shape[0])

report += ["", f"**{fails} check(s) failed.**" if fails else "**All checks passed.**"]
(LOGS / "checks_report.txt").write_text("\n".join(report))
log.info("\n" + "\n".join(report))
if fails: sys.exit(f"{fails} check(s) failed -- see logs/checks_report.txt")
log.info("03_checks done")
