"""
04_codebook.py -- LFS: generate CODEBOOK.md (+ codebook_<unit>.csv) from the final files.

For every variable in each 3_Final file: label, storage type, value labels (first few),
non-missing count per year, the raw source variable per year (key block), and the
alignment decision + label variants recorded by 02_merge.py.
"""
import json
import numpy as np, pandas as pd
from lfs_helpers import paths, get_logger, read_dta, read_meta, LOGS, HERE, DATASET

log = get_logger("04_codebook")
P = paths()
align = json.load(open(LOGS / "merge_alignment.json"))
srcs = {y: json.load(open(LOGS / f"clean_{y}_meta.json"))["source"] for y in range(2017, 2026)}

def chunked_counts(path, key, chunk=250_000):
    """non-missing counts per column by `key` (wave/year), reading the file in row chunks so
    multi-GB pooled files never sit in memory whole; returns (counts DataFrame, ordered key values, n rows)."""
    m = read_meta(path); counts, order = None, []
    for off in range(0, m.number_rows, chunk):
        part, _, _ = read_dta(path, row_offset=off, row_limit=chunk)
        if key not in part.columns: part[key] = "all"
        c = part.groupby(key, sort=False).count()
        counts = c if counts is None else counts.add(c, fill_value=0)
        order += [k for k in part[key].unique().tolist() if k not in order]
    return counts.reindex(order).fillna(0).astype(int), order, int(m.number_rows)


def codebook(fname, unit):
    df, vl, vv = read_dta(P["final"] / fname, row_limit=1)          # one row: columns and dtypes only
    m = read_meta(P["final"] / fname)
    types = m.readstat_variable_types
    nn, years, nrows = chunked_counts(P["final"] / fname, "year")
    rows = []
    for c in df.columns:
        base = c.rsplit("_v", 1)[0] if ("_v" in c and c.rsplit("_v", 1)[-1].isdigit()) else c
        d = align["decisions"].get(base) or {}
        vers = d.get("versions") or {}
        ys_here = vers.get(c, [])
        labs = {y: l for y, l in (d.get("labels_by_year") or {}).items() if int(y) in ys_here}
        variants = "; ".join(f"{y}: {l[:60]}" for y, l in labs.items() if l and l != d.get("reference_label")) if len(set(labs.values())) > 1 else ""
        other_versions = ", ".join(f"{n} ({ys[0]}–{ys[-1]})" for n, ys in vers.items() if n != c) if len(vers) > 1 else ""
        src = "; ".join(f"{y}: {s[c]}" for y, s in srcs.items() if c in s)
        vlab = vv.get(c, {})
        vtxt = ", ".join(f"{k}={v}" for k, v in list(vlab.items())[:6]) + (" …" if len(vlab) > 6 else "")
        conf = align["value_label_conflicts"].get(c)
        rows.append({"variable": c, "label": vl.get(c) or "", "type": types.get(c, str(df[c].dtype)),
                     "value_labels": vtxt, "n_value_labels": len(vlab),
                     **{f"n_{y}": int(nn.loc[y, c]) if c in nn.columns else 0 for y in years},
                     "source_by_year": src, "version_years": ",".join(map(str, ys_here)) if len(vers) > 1 else "",
                     "other_versions": other_versions,
                     "label_variants": variants, "value_label_conflicts": json.dumps(conf) if conf else ""})
    cb = pd.DataFrame(rows)
    cb.to_csv(HERE / f"codebook_{unit}.csv", index=False)
    md = [f"## `{fname}` — one row per {unit}-interview", "",
          f"{nrows:,} rows × {df.shape[1]} variables. Years: {', '.join(map(str, years))}.", "",
          "| variable | label | type | value labels | " + " | ".join(f"N {y}" for y in years) + " | notes |",
          "|---|---|---|---|" + "---:|" * len(years) + "---|"]
    for r in rows:
        notes = []
        if r["source_by_year"]: notes.append("source: " + r["source_by_year"])
        if r["version_years"]: notes.append(f"version for {r['version_years']}; other versions: {r['other_versions']}")
        if r["label_variants"]: notes.append("label variants — " + r["label_variants"])
        if r["value_label_conflicts"]: notes.append("value-label text conflicts: " + r["value_label_conflicts"])
        md.append("| `" + r["variable"] + "` | " + r["label"].replace("|", "/") + " | " + str(r["type"]) + " | " +
                  r["value_labels"].replace("|", "/") + " | " + " | ".join(f"{r[f'n_{y}']:,}" for y in years) + " | " +
                  "; ".join(notes).replace("|", "/") + " |")
    return md

out = ["# LFS codebook", "", "Generated by `04_codebook.py` from `3_Final/`. Do not hand-edit; see `DECISIONS.md` for the reasoning.", "",
       "Key block (identical names in every NISR dataset): `survey year wave round quarter interview prov dist urban cluster psu hhid pid wt wt_round`.",
       f"Alignment rule: years are grouped into versions of a variable by label similarity (token Jaccard ≥ {align['threshold']}); the largest group keeps the name, the others are `<name>_v2`, `_v3` …; forced alignments: {', '.join(sorted(align.get('force_align', [])))}. "
       "Value labels are the union over years; where the same code had different text the most recent year's text is kept and the conflict listed.", ""]
out += codebook("LFS_pooled_person.dta", "person") + [""] + codebook("LFS_pooled_household.dta", "household")
(HERE / "CODEBOOK.md").write_text("\n".join(out))
log.info("wrote CODEBOOK.md, codebook_person.csv, codebook_household.csv")

# ---------------------------------------------------------------- README.txt on Dropbox
# The dataset folder's README.txt keeps its hand-written sections; the block between the two
# marker lines below is regenerated from 3_Final/ and 2_Intermediate/ on every run, and the
# pre-pipeline sentences that are now stale are replaced by a pointer to the git folder.
def update_readme():
    import re, time
    from pathlib import Path
    readme = P["root"] / "README.txt"
    if not readme.exists(): log.warning("no README.txt in %s; skipped", P["root"]); return
    start, end = "=== PROCESSED OUTPUTS (generated by 04_codebook.py; do not edit inside) ===", "=== END PROCESSED OUTPUTS ==="
    finals = sorted(P["final"].glob("*.dta")); inters = sorted(P["inter"].glob("*.dta"))
    lines = [start, f"Pipeline: rwa-trs/NISR/{DATASET}/  (python master.py)   last run: {time.strftime('%Y-%m-%d %H:%M')}",
             f"Code, decisions (DECISIONS.md), codebook (CODEBOOK.md) and run logs live in the git repository, not here.", "",
             f"3_Final/  ({len(finals)} files)"]
    for f in finals:
        try:
            m = read_meta(f); lines.append(f"  {f.name:55s} {m.number_rows:>10,} rows x {len(m.column_names):>4} vars   {m.file_label or ''}")
        except Exception as e: lines.append(f"  {f.name:55s} (unreadable: {e})")
    app = sorted((P["inter"] / "appended").glob("*.dta")) if (P["inter"] / "appended").exists() else []
    lines += ["", f"2_Intermediate/  ({len(inters)} files: one cleaned file per wave and unit/module; see CODEBOOK.md)"]
    if app:
        lines.append(f"2_Intermediate/appended/  ({len(app)} module-level files appended across waves)")
        for f in app:
            try: m = read_meta(f); lines.append(f"  {f.name:55s} {m.number_rows:>10,} rows x {len(m.column_names):>4} vars")
            except Exception as e: lines.append(f"  {f.name:55s} (unreadable: {e})")
    lines.append(end)
    txt = readme.read_text(encoding="utf-8", errors="replace")
    for stale in ["2_Intermediate/ and 3_Final/ are empty: no clean.do / merge.do written for\nthis survey yet. The Census, EICV and LFS folders have working examples.",
                  "2_Intermediate/  0 files (not built yet)", "3_Final/         0 files (not built yet)"]:
        txt = txt.replace(stale, "Processed by the Python pipeline in rwa-trs/NISR/ (see the PROCESSED OUTPUTS block).")
    txt = re.sub(r"Code lives in code/Publicly Available Data - NISR/ and was repointed to these\npaths on the same date \(previous paths under \"Rwanda - Tourism, Green Jobs/\nData/Public\" were already stale\).",
                 "Code now lives in the git repository rwa-trs/NISR/<dataset>/ (Python); the Stata\ndo-files are archived in Rwanda - TRS/_archive/code-NISR-stata-2026-09-04/.", txt)
    new_block = "\n".join(lines)
    if start in txt and end in txt:
        txt = txt[:txt.index(start)] + new_block + txt[txt.index(end) + len(end):]
    else:
        head_end = txt.find("\n\n") + 2 if "\n\n" in txt[:600] else 0
        txt = txt[:head_end] + new_block + "\n\n" + txt[head_end:]
    readme.write_text(txt, encoding="utf-8"); log.info("README.txt updated (%s)", readme)

update_readme()
