"""
03_checks.py -- CFSVA: verification of 3_Final/ -> logs/checks_report.txt
  A. pooled files vs per-wave files   B. Stata 17 recomputation   C. geography completeness and documented sample sizes
  D. keys and identities (CFSVA audit 2026-09-05): cluster completeness and counts by wave, 2012 urban distribution,
     2015 woman / child rows carry no household id, woman / child rows link to households elsewhere, 2018 = report count
  E. cross-wave coding compatibility within every pooled column (re-derived from the per-wave meta files)
Rows with a reference are hard checks; rows without one are informational.
"""
import difflib, json, os, re, shutil, subprocess, sys
import pandas as pd
from cfsva_helpers import paths, get_logger, read_dta, read_meta, LOGS, HERE, NameTable, DATASET_TAG
log = get_logger("03_checks"); P = paths()
NAMES = NameTable(HERE / "variable_names.csv", DATASET_TAG)
_METAS = {f.stem[6:-5]: json.load(open(f)) for f in LOGS.glob("clean_*_meta.json")}
_OUT2ENTRY = {e["out"]: (y, tag, e) for y, m in _METAS.items() for tag, e in m.get("files", {}).items() if e.get("out")}
def read_native_cols(path, natives, scope=None):
    """columns of a written file by their native names (pooled: scope pooled:<file>; per-wave: the meta's clean_names map)"""
    if scope is None:
        y, tag, e = _OUT2ENTRY[path.name]; cl = e["clean_names"]; inv = {c: n for n, c in cl.items()}
    else: cl = NAMES.clean(scope); inv = NAMES.native(scope)
    df, _, _ = read_dta(path, usecols=[cl[c] for c in natives if c in cl]); return df.rename(columns=inv)
def native_cols_of(fname, wanted):
    """the native columns of `wanted` present in the pooled file (its columns carry clean names)"""
    names = set(read_meta(P["final"] / fname).column_names); cl = NAMES.clean(f"pooled:{fname}")
    return [c for c in wanted if cl.get(c) in names]
report = ["# CFSVA checks report", "", "Generated by 03_checks.py.", ""]; fails = 0
def row(section, name, ours, ref, tol=0.0):
    global fails
    ok = None if ref is None else abs(float(ours) - float(ref)) <= tol * max(1.0, abs(float(ref)))
    fails += (ok is False)
    report.append(f"| {section} | {name} | {ours:,.0f} | {'' if ref is None else f'{ref:,.0f}'} | {'PASS' if ok else ('n/a' if ok is None else '**FAIL**')} |")
units = [u for u in ("household", "woman", "child", "village") if (P["final"] / f"CFSVA_pooled_{u}.dta").exists()]
report += ["## A. Pooled files vs per-wave cleaned files", "", "| section | statistic | Python | reference | result |", "|---|---|---:|---:|---|"]
hh = None; pooled = {}
_al0 = json.load(open(LOGS / "merge_alignment.json"))
row("A", "exact duplicate rows dropped before saving the pooled files (Matteo's rule; all files; informational)", sum(sum(i.get("duplicates_dropped", {}).values()) for i in _al0["files"].values()), None)
for u in units:
    DUP = _al0["files"].get(f"CFSVA_pooled_{u}.dta", {}).get("duplicates_dropped", {}); DUPW = _al0["files"].get(f"CFSVA_pooled_{u}.dta", {}).get("wt_dropped", {})
    cols = native_cols_of(f"CFSVA_pooled_{u}.dta", ["wave", "wt", "dist", "hhid", "cluster", "urban"])
    d = read_native_cols(P["final"] / f"CFSVA_pooled_{u}.dta", cols, f"pooled:CFSVA_pooled_{u}.dta"); pooled[u] = d
    if u == "household": hh = d
    for w, g in d.groupby("wave", sort=False):
        p = read_native_cols(P["inter"] / f"CFSVA_{w}_{u}_clean.dta", [c for c in cols if c != "wave"])
        dr, dw = DUP.get(w, 0), DUPW.get(w, 0.0)
        row("A", f"{w} {u} rows" + (f" (+{dr} exact duplicates dropped)" if dr else ""), len(g), len(p) - dr)
        if "wt" in g and "wt" in p and g["wt"].notna().any(): row("A", f"{w} {u} sum wt", g["wt"].sum(), p["wt"].sum() - dw, 1e-9)
report += ["", "## B. Stata 17 recomputation (household file)", ""]
stata = "/Applications/Stata/StataMP.app/Contents/MacOS/stata-mp"
if not os.path.exists(stata): stata = shutil.which("stata-mp") or shutil.which("stata")
if stata and hh is not None:
    do, out = HERE / "stata_checks.do", LOGS / "stata_checks.csv"
    do.write_text(f'''* stata_checks.do -- recompute CFSVA check statistics in Stata (written by 03_checks.py)
clear all
set more off
use {" ".join(NAMES.clean("pooled:CFSVA_pooled_household.dta")[c] for c in ("wave", "wt", "dist"))} using "{P["final"] / "CFSVA_pooled_household.dta"}", clear
rename ({" ".join(NAMES.clean("pooled:CFSVA_pooled_household.dta")[c] for c in ("wave", "wt", "dist"))}) (wave wt dist)
gen long one = 1
bysort wave dist: gen byte first_dist = _n == 1
collapse (sum) n=one sum_wt=wt n_dist=first_dist, by(wave)
export delimited using "{out}", replace
''')
    r = subprocess.run([stata, "-q", "-b", "do", str(do)], cwd=str(HERE), capture_output=True, text=True); logf = HERE / "stata_checks.log"
    if out.exists():
        st = pd.read_csv(out, dtype={"wave": str}).set_index("wave"); report += ["| section | statistic | Python | Stata | result |", "|---|---|---:|---:|---|"]
        for w, g in hh.groupby("wave", sort=False):
            s = st.loc[w]; row("B", f"{w} households", len(g), s["n"]); row("B", f"{w} districts", g["dist"].nunique(), s["n_dist"])
            if g["wt"].notna().any(): row("B", f"{w} sum wt", g["wt"].sum(), s["sum_wt"], 1e-6)
        if logf.exists(): (LOGS / "stata_checks.log").write_text(logf.read_text()); logf.unlink()
    else: report.append(f"Stata run produced no output (rc={r.returncode})"); fails += 1
else: report.append("Stata not found -- section B skipped.")
report += ["", "## C. Geography completeness (household file)", "", "| section | statistic | Python | reference | result |", "|---|---|---:|---:|---|"]
# sample sizes stated in the methodology annexes (NISR-Food-Security-CFSVAN.md (documentation notes)); 2018 is shipped larger than documented (informational)
for w, n in {"2012": 7_498, "2015": 7_500, "2021": 9_000, "2024": 9_000}.items():
    if (hh["wave"] == w).any(): row("C", f"{w} households vs methodology annex ({n:,})", int((hh["wave"] == w).sum()), n)
if (hh["wave"] == "2018").any(): row("C", "2018 households vs the final report (9,709 interviewed; the annex target was 9,000)", int((hh["wave"] == "2018").sum()), 9_709)
for uname, w, n in (("woman", "2015", 6_768), ("village", "2012", 748), ("village", "2015", 750), ("village", "2021", 900)):
    f = P["final"] / f"CFSVA_pooled_{uname}.dta"
    if f.exists():
        u = read_native_cols(f, ["wave"], f"pooled:{f.name}"); row("C", f"{w} {uname} records vs methodology annex ({n:,})", int((u["wave"] == w).sum()), n)
        if uname == "village" and (u["wave"] == "2018").any(): row("C", "2018 village records in the shipped file (annex says 749; informational)", int((u["wave"] == "2018").sum()), None)
if hh is not None:
    for w, g in hh.groupby("wave", sort=False):
        expected = {"2006": 29, "2009": 27}.get(w, 30)      # 2006 covered 29 districts; 2009 excluded the three City of Kigali districts
        row("C", f"{w} districts present (survey coverage)", g["dist"].nunique(), expected); row("C", f"{w} rows with district", int(g["dist"].notna().sum()), len(g), 0.01)
# ---------------------------------------------------------------- D. keys and identities
report += ["", "## D. Keys and identities", "", "| section | statistic | Python | reference | result |", "|---|---|---:|---:|---|"]
CL = {"2006": True, "2009": True, "2012": True, "2015": True, "2018": False, "2021": False, "2024": False}      # cluster available (2015: reconstructed) / no PSU released
for w, g in hh.groupby("wave", sort=False):
    has = int((g["cluster"].fillna("") != "").sum())
    if CL.get(w): row("D", f"{w} households with a cluster id (must be all)", has, len(g))
    else: row("D", f"{w} households with a cluster id (no PSU in the public file; informational)", has, None)
for w, n, what in (("2009", 449, "enumeration zones (province-district-zone composite; report: 450, one 24-household zone)"), ("2012", 750, "villages (vill_id)"), ("2015", 750, "reconstructed villages (25 per district x 30)")):
    g = hh[hh["wave"] == w]
    if len(g): row("D", f"{w} distinct clusters = {what}", g["cluster"].nunique(), n)
g = hh[hh["wave"] == "2015"]
if len(g): row("D", "2015 reconstructed villages: households per village = 10 (number of villages with another size)", int((g.groupby("cluster").size() != 10).sum()), 0)
g = hh[hh["wave"] == "2012"]
if len(g) and "urban" in g:
    row("D", "2012 urban == 1 (NISR urban_new: 990)", int((g["urban"] == 1).sum()), 990); row("D", "2012 urban == 2 (6,508)", int((g["urban"] == 2).sum()), 6_508); row("D", "2012 urban missing", int(g["urban"].isna().sum()), 0)
for u in ("woman", "child"):
    if u not in pooled: continue
    d = pooled[u]
    for w, g in d.groupby("wave", sort=False):
        ids = g["hhid"].dropna() if "hhid" in g else pd.Series(dtype=object)
        ids = ids[ids.astype(str).str.strip() != ""]
        if w == "2015": row("D", f"2015 {u} rows carrying a household id (must be 0: nutrition-form ids only)", len(ids), 0)
        else:
            hw = hh.loc[hh["wave"] == w, "hhid"].astype(str)
            row("D", f"{w} {u} rows whose household id is in the household file (share x 1000; must be >= 900; 2012 children link at 93.9% as shipped)", 1000 * ids.astype(str).isin(hw).mean() if len(ids) else 0, 1000, 0.1)

# ---------------------------------------------------------------- E. cross-wave coding compatibility (independent of 02_merge: from the per-wave meta files)
align = json.load(open(LOGS / "merge_alignment.json")); thr = align.get("vl_threshold", 0.6)
metas = {f.stem.replace("clean_", "").replace("_meta", ""): json.load(open(f)) for f in LOGS.glob("clean_*_meta.json")}
SENT = {98, 99, 998, 999, 9998, 9999}
MISSING_LIKE = {"not stated", "missing", "dont know", "dk", "unknown", "not known", "non determine", "nd", "ns", "not applicable", "na"}
_SYN = {"others": "other", "yego": "yes", "oya": "no", "specify": "", "please": "", "specified": ""}
def _norm(s): return " ".join(w for w in (_SYN.get(x, x) for x in re.sub(r"[^a-z0-9]+", " ", str(s).lower()).split()) if w)
def _same(x, y):
    a, b = _norm(x), _norm(y)
    if a == b or (a in MISSING_LIKE and b in MISSING_LIKE): return True
    ta, tb = set(a.split()), set(b.split())
    if ta and tb and (ta <= tb or tb <= ta): return True
    return difflib.SequenceMatcher(None, a, b).ratio() >= thr
bad, nsplit, nsplit_vl = [], 0, 0
for fname, info in align["files"].items():
    unit = info.get("unit")
    for base, d in info["decisions"].items():
        if len(d["versions"]) > 1:
            nsplit += 1
            if any("value labels" in r or "unlabelled" in r for r in d.get("split_reasons", [])): nsplit_vl += 1
        for col, ws in d["versions"].items():
            labs = [(w, {float(k): v for k, v in metas[w]["files"][unit].get("value_labels", {}).get(base, {}).items() if str(k).replace('.', '', 1).lstrip('-').isdigit()}) for w in ws if w in metas and unit in metas[w].get("files", {})]
            for i in range(len(labs)):
                for j in range(i + 1, len(labs)):
                    a, b = labs[i][1], labs[j][1]
                    for c in set(a) & set(b):
                        if c not in SENT and not _same(a[c], b[c]): bad.append((fname, col, labs[i][0], labs[j][0], c, a[c], b[c]))
report += ["", "## E. Cross-wave coding compatibility within pooled columns (all pooled files)", "", "| section | statistic | Python | reference | result |", "|---|---|---:|---:|---|"]
row("E", "pooled columns holding waves with incompatible value-label texts for the same code (must be 0)", len({(b[0], b[1]) for b in bad}), 0)
row("E", "variables split into versions, all pooled files (informational)", nsplit, None)
row("E", "of which because of value labels or unlabelled ranges (informational)", nsplit_vl, None)
row("E", "variables with codes observed outside their own wave's value labels -- stale labels (informational)", sum(len(i.get("stale_labels", {})) for i in align["files"].values()), None)
if bad: report += ["", "Incompatible pairs: " + "; ".join(f"{f}:{c}: {y1}/{y2} code {k:g} {p!r} vs {q!r}" for f, c, y1, y2, k, p, q in bad[:20])]
report += ["", f"**{fails} check(s) failed.**" if fails else "**All checks passed.**"]
(LOGS / "checks_report.txt").write_text("\n".join(report)); log.info("\n" + "\n".join(report))
if fails: sys.exit(f"{fails} check(s) failed -- see logs/checks_report.txt")
log.info("03_checks done")
