"""
03_checks.py -- CFSVA: verification of 3_Final/ -> logs/checks_report.txt
  A. pooled files vs per-wave files   B. Stata 17 recomputation   C. geography completeness
"""
import os, shutil, subprocess, sys
import pandas as pd
from cfsva_helpers import paths, get_logger, read_dta, read_meta, LOGS, HERE
log = get_logger("03_checks"); P = paths()
report = ["# CFSVA checks report", "", "Generated by 03_checks.py.", ""]; fails = 0
def row(section, name, ours, ref, tol=0.0):
    global fails
    ok = None if ref is None else abs(float(ours) - float(ref)) <= tol * max(1.0, abs(float(ref)))
    fails += (ok is False)
    report.append(f"| {section} | {name} | {ours:,.0f} | {'' if ref is None else f'{ref:,.0f}'} | {'PASS' if ok else ('n/a' if ok is None else '**FAIL**')} |")
units = [u for u in ("household", "woman", "child", "village") if (P["final"] / f"CFSVA_pooled_{u}.dta").exists()]
report += ["## A. Pooled files vs per-wave cleaned files", "", "| section | statistic | Python | reference | result |", "|---|---|---:|---:|---|"]
hh = None
for u in units:
    cols = [c for c in ["wave", "wt", "dist", "hhid"] if c in read_meta(P["final"] / f"CFSVA_pooled_{u}.dta").column_names]
    d, _, _ = read_dta(P["final"] / f"CFSVA_pooled_{u}.dta", usecols=cols)
    if u == "household": hh = d
    for w, g in d.groupby("wave", sort=False):
        p, _, _ = read_dta(P["inter"] / f"CFSVA_{w}_{u}_clean.dta", usecols=[c for c in cols if c != "wave"])
        row("A", f"{w} {u} rows", len(g), len(p))
        if "wt" in g and "wt" in p and g["wt"].notna().any(): row("A", f"{w} {u} sum wt", g["wt"].sum(), p["wt"].sum(), 1e-9)
report += ["", "## B. Stata 17 recomputation (household file)", ""]
stata = "/Applications/Stata/StataMP.app/Contents/MacOS/stata-mp"
if not os.path.exists(stata): stata = shutil.which("stata-mp") or shutil.which("stata")
if stata and hh is not None:
    do, out = HERE / "stata_checks.do", LOGS / "stata_checks.csv"
    do.write_text(f'''* stata_checks.do -- recompute CFSVA check statistics in Stata (written by 03_checks.py)
clear all
set more off
use wave wt dist using "{P["final"] / "CFSVA_pooled_household.dta"}", clear
gen long one = 1
bysort wave dist: gen byte first_dist = _n == 1
collapse (sum) n=one sum_wt=wt n_dist=first_dist, by(wave)
export delimited using "{out}", replace
''')
    r = subprocess.run([stata, "-q", "-b", "do", str(do)], cwd=str(HERE), capture_output=True, text=True); logf = HERE / "stata_checks.log"
    if out.exists():
        st = pd.read_csv(out, dtype={"wave": str}).set_index("wave"); report += ["| section | statistic | Python | Stata | result |", "|---|---|---:|---:|---|"]
        for w, g in hh.groupby("wave", sort=False):
            s = st.loc[w]; row("B", f"{w} households", len(g), s["n"]); row("B", f"{w} districts", g["dist"].nunique(), s["n_dist"])
            if g["wt"].notna().any(): row("B", f"{w} sum wt", g["wt"].sum(), s["sum_wt"], 1e-6)
        if logf.exists(): (LOGS / "stata_checks.log").write_text(logf.read_text()); logf.unlink()
    else: report.append(f"Stata run produced no output (rc={r.returncode})"); fails += 1
else: report.append("Stata not found -- section B skipped.")
report += ["", "## C. Geography completeness (household file)", "", "| section | statistic | Python | reference | result |", "|---|---|---:|---:|---|"]
# sample sizes stated in the methodology annexes (NISR-Food-Security-CFSVAN.md (documentation notes)); 2018 is shipped larger than documented (informational)
for w, n in {"2012": 7_498, "2015": 7_500, "2021": 9_000, "2024": 9_000}.items():
    if (hh["wave"] == w).any(): row("C", f"{w} households vs methodology annex ({n:,})", int((hh["wave"] == w).sum()), n)
if (hh["wave"] == "2018").any(): row("C", "2018 households in the shipped file (annex says 9,000; informational)", int((hh["wave"] == "2018").sum()), None)
for uname, w, n in (("woman", "2015", 6_768), ("village", "2012", 748)):
    f = P["final"] / f"CFSVA_pooled_{uname}.dta"
    if f.exists():
        u, _, _ = read_dta(f, usecols=["wave"]); row("C", f"{w} {uname} records vs methodology annex ({n:,})", int((u["wave"] == w).sum()), n)
        if uname == "village" and (u["wave"] == "2018").any(): row("C", "2018 village records in the shipped file (annex says 749; informational)", int((u["wave"] == "2018").sum()), None)
if hh is not None:
    for w, g in hh.groupby("wave", sort=False):
        expected = {"2006": 29, "2009": 27}.get(w, 30)      # 2006 covered 29 districts; 2009 excluded the three City of Kigali districts
        row("C", f"{w} districts present (survey coverage)", g["dist"].nunique(), expected); row("C", f"{w} rows with district", int(g["dist"].notna().sum()), len(g), 0.01)
report += ["", f"**{fails} check(s) failed.**" if fails else "**All checks passed.**"]
(LOGS / "checks_report.txt").write_text("\n".join(report)); log.info("\n" + "\n".join(report))
if fails: sys.exit(f"{fails} check(s) failed -- see logs/checks_report.txt")
log.info("03_checks done")
