"""
04_codebook.py -- CFSVA: generate CODEBOOK.md (+ codebook_<file>.csv) for every file in 3_Final/.

Per variable: label, storage type, value labels (first few), non-missing count per wave, the
source per wave recorded by 01_clean (person/household files), version decisions and label
variants recorded by 02_merge.
"""
import json
import pandas as pd
from cfsva_helpers import paths, get_logger, read_dta, read_meta, LOGS, HERE, DATASET

log = get_logger("04_codebook"); P = paths()
align = json.load(open(LOGS / "merge_alignment.json"))
metas = {f.stem.replace("clean_", "").replace("_meta", ""): json.load(open(f)) for f in LOGS.glob("clean_*_meta.json")}

def codebook(fname, info):
    df, vl, vv = read_dta(P["final"] / fname); m = read_meta(P["final"] / fname); types = m.readstat_variable_types
    waves = list(dict.fromkeys(df["wave"].tolist())) if "wave" in df else ["all"]
    nn = df.groupby("wave").count() if "wave" in df else None
    decisions = info.get("decisions", {}); rows = []
    unit = info.get("unit", "")
    for c in df.columns:
        base = next((b for b, d in decisions.items() if c in d.get("versions", {})), c)
        d = decisions.get(base, {}); vers = d.get("versions", {}); ws_here = vers.get(c, [])
        labs = {w: l for w, l in (d.get("labels_by_wave") or {}).items() if w in ws_here}
        variants = "; ".join(f"{w}: {l[:50]}" for w, l in labs.items() if l and l != d.get("reference_label")) if len(set(labs.values())) > 1 else ""
        others = ", ".join(f"{n} ({', '.join(g)})" for n, g in vers.items() if n != c) if len(vers) > 1 else ""
        src = "; ".join(f"{w}: {metas[w][unit]['source'][c]}" for w in ws_here if w in metas and unit in metas[w] and c in metas[w][unit].get("source", {}))
        vlab = vv.get(c, {}); vtxt = ", ".join(f"{k}={v}" for k, v in list(vlab.items())[:5]) + (" …" if len(vlab) > 5 else "")
        conf = info.get("value_label_conflicts", {}).get(c)
        rows.append({"variable": c, "label": vl.get(c) or "", "type": types.get(c, ""), "value_labels": vtxt, "n_value_labels": len(vlab),
                     **{f"n_{w}": int(nn.loc[w, c]) if nn is not None and w in nn.index and c in nn.columns else len(df) for w in waves},
                     "source": src, "versions": others, "label_variants": variants, "value_label_conflicts": json.dumps(conf) if conf else ""})
    cb = pd.DataFrame(rows); cb.to_csv(HERE / f"codebook_{fname[:-4]}.csv", index=False)
    md = [f"## `{fname}` — one row per {unit}", "", f"{len(df):,} rows × {df.shape[1]} variables. Waves: {', '.join(waves)}.", "",
          "| variable | label | type | value labels | " + " | ".join(f"N {w}" for w in waves) + " | notes |", "|---|---|---|---|" + "---:|" * len(waves) + "---|"]
    for r in rows:
        notes = [x for x in (("source: " + r["source"]) if r["source"] else "", ("other versions: " + r["versions"]) if r["versions"] else "",
                             ("label variants — " + r["label_variants"]) if r["label_variants"] else "",
                             ("value-label text conflicts: " + r["value_label_conflicts"]) if r["value_label_conflicts"] else "") if x]
        md.append("| `" + r["variable"] + "` | " + r["label"].replace("|", "/") + " | " + str(r["type"]) + " | " + r["value_labels"].replace("|", "/") +
                  " | " + " | ".join(f"{r[f'n_{w}']:,}" for w in waves) + " | " + "; ".join(notes).replace("|", "/") + " |")
    return md

out = ["# CFSVA codebook", "", "Generated by `04_codebook.py` from `3_Final/`. Do not hand-edit; see `DECISIONS.md` for the reasoning.", "",
       "Key block: `survey year wave unit prov dist sector urban cluster hhid wt`.",
       f"Alignment rule: waves are grouped into versions of a variable by label similarity (token Jaccard ≥ {align['threshold']}); the largest group keeps the name, "
       "the others are `<name>_v2`, `_v3` …. Value labels are the union within a version; where the same code had different text the most recent wave's text is kept and the conflict listed.", "",
       "Files: " + ", ".join(f"`{f}` ({i.get('unit')}, {i['rows']:,} rows)" for f, i in align["files"].items()), ""]
for fname, info in align["files"].items():
    out += codebook(fname, info) + [""]
(HERE / "CODEBOOK.md").write_text("\n".join(out)); log.info("wrote CODEBOOK.md and codebook_*.csv for %d files", len(align["files"]))

# ---------------------------------------------------------------- README.txt on Dropbox
# The dataset folder's README.txt keeps its hand-written sections; the block between the two
# marker lines below is regenerated from 3_Final/ and 2_Intermediate/ on every run, and the
# pre-pipeline sentences that are now stale are replaced by a pointer to the git folder.
def update_readme():
    import re, time
    from pathlib import Path
    readme = P["root"] / "README.txt"
    if not readme.exists(): log.warning("no README.txt in %s; skipped", P["root"]); return
    start, end = "=== PROCESSED OUTPUTS (generated by 04_codebook.py; do not edit inside) ===", "=== END PROCESSED OUTPUTS ==="
    finals = sorted(P["final"].glob("*.dta")); inters = sorted(P["inter"].glob("*.dta"))
    lines = [start, f"Pipeline: rwa-trs/NISR/{DATASET}/  (python master.py)   last run: {time.strftime('%Y-%m-%d %H:%M')}",
             f"Code, decisions (DECISIONS.md), codebook (CODEBOOK.md) and run logs live in the git repository, not here.", "",
             f"3_Final/  ({len(finals)} files)"]
    for f in finals:
        try:
            m = read_meta(f); lines.append(f"  {f.name:55s} {m.number_rows:>10,} rows x {len(m.column_names):>4} vars   {m.file_label or ''}")
        except Exception as e: lines.append(f"  {f.name:55s} (unreadable: {e})")
    lines += ["", f"2_Intermediate/  ({len(inters)} files: one cleaned file per wave and unit/module; see CODEBOOK.md)", end]
    txt = readme.read_text(encoding="utf-8", errors="replace")
    for stale in ["2_Intermediate/ and 3_Final/ are empty: no clean.do / merge.do written for\nthis survey yet. The Census, EICV and LFS folders have working examples.",
                  "2_Intermediate/  0 files (not built yet)", "3_Final/         0 files (not built yet)"]:
        txt = txt.replace(stale, "Processed by the Python pipeline in rwa-trs/NISR/ (see the PROCESSED OUTPUTS block).")
    txt = re.sub(r"Code lives in code/Publicly Available Data - NISR/ and was repointed to these\npaths on the same date \(previous paths under \"Rwanda - Tourism, Green Jobs/\nData/Public\" were already stale\).",
                 "Code now lives in the git repository rwa-trs/NISR/<dataset>/ (Python); the Stata\ndo-files are archived in Rwanda - TRS/_archive/code-NISR-stata-2026-09-04/.", txt)
    new_block = "\n".join(lines)
    if start in txt and end in txt:
        txt = txt[:txt.index(start)] + new_block + txt[txt.index(end) + len(end):]
    else:
        head_end = txt.find("\n\n") + 2 if "\n\n" in txt[:600] else 0
        txt = txt[:head_end] + new_block + "\n\n" + txt[head_end:]
    readme.write_text(txt, encoding="utf-8"); log.info("README.txt updated (%s)", readme)

update_readme()
