"""
03_checks.py -- AHS: independent verification of 3_Final/ outputs -> logs/checks_report.md
  A. Pooled files vs per-wave files (rows, weights)     B. Stata 17 recomputation     C. household/person consistency
"""
import os, shutil, subprocess, sys
import pandas as pd
from ahs_helpers import paths, get_logger, read_dta, read_meta, LOGS, HERE

log = get_logger("03_checks"); P = paths()
report = ["# AHS checks report", "", "Generated by 03_checks.py.", ""]; fails = 0
def row(section, name, ours, ref, tol=0.0):
    global fails
    ok = None if ref is None else abs(float(ours) - float(ref)) <= tol * max(1.0, abs(float(ref)))
    fails += (ok is False)
    report.append(f"| {section} | {name} | {ours:,.0f} | {'' if ref is None else f'{ref:,.0f}'} | {'PASS' if ok else ('n/a' if ok is None else '**FAIL**')} |")

person, _, _ = read_dta(P["final"] / "AHS_pooled_person.dta", usecols=["wave", "wt", "sex", "dist", "hhid"])
hh, _, _ = read_dta(P["final"] / "AHS_pooled_household.dta", usecols=["wave", "wt", "hhsize", "hhid"])
ours = {w: {"n": len(g), "sum_wt": g["wt"].sum(), "n_hh": g["hhid"].nunique(), "male": int((g["sex"] == 1).sum()), "female": int((g["sex"] == 2).sum()), "n_dist": g["dist"].nunique()} for w, g in person.groupby("wave", sort=False)}
report += ["## A. Pooled person file vs per-wave cleaned files", "", "| section | statistic | Python | reference | result |", "|---|---|---:|---:|---|"]
for w in ours:
    p, _, _ = read_dta(P["inter"] / f"AHS_{w}_person_clean.dta", usecols=["wt", "hhid"])
    row("A", f"{w} person rows", ours[w]["n"], len(p)); row("A", f"{w} sum wt", ours[w]["sum_wt"], p["wt"].sum(), 1e-9); row("A", f"{w} households", ours[w]["n_hh"], p["hhid"].nunique()); row("A", f"{w} districts", ours[w]["n_dist"], 30)
report += ["", "## B. Stata 17 recomputation from the written .dta files", ""]
stata = "/Applications/Stata/StataMP.app/Contents/MacOS/stata-mp"
if not os.path.exists(stata): stata = shutil.which("stata-mp") or shutil.which("stata")
if stata:
    do, out, outh = HERE / "stata_checks.do", LOGS / "stata_checks.csv", LOGS / "stata_checks_hh.csv"
    do.write_text(f'''* stata_checks.do -- recompute AHS check statistics in Stata (written by 03_checks.py)
clear all
set more off
use wave wt sex hhid using "{P["final"] / "AHS_pooled_person.dta"}", clear
gen byte male = sex == 1
gen byte female = sex == 2
gen long one = 1
bysort wave hhid: gen byte first_hh = _n == 1
collapse (sum) n=one sum_wt=wt male female n_hh=first_hh, by(wave)
export delimited using "{out}", replace
use wave wt hhsize hhid using "{P["final"] / "AHS_pooled_household.dta"}", clear
collapse (count) n_hh=hhid (sum) hhsize_sum=hhsize sum_wt_hh=wt, by(wave)
export delimited using "{outh}", replace
''')
    r = subprocess.run([stata, "-q", "-b", "do", str(do)], cwd=str(HERE), capture_output=True, text=True)
    logf = HERE / "stata_checks.log"
    if out.exists() and outh.exists():
        st, sth = pd.read_csv(out, dtype={"wave": str}).set_index("wave"), pd.read_csv(outh, dtype={"wave": str}).set_index("wave")
        report += ["| section | statistic | Python | Stata | result |", "|---|---|---:|---:|---|"]
        for w in ours:
            o, s = ours[w], st.loc[w]
            row("B", f"{w} person rows", o["n"], s["n"]); row("B", f"{w} sum wt", o["sum_wt"], s["sum_wt"], 1e-9); row("B", f"{w} male", o["male"], s["male"]); row("B", f"{w} female", o["female"], s["female"])
        for w, g in hh.groupby("wave", sort=False):
            row("B", f"{w} households", len(g), sth.loc[w, "n_hh"]); row("B", f"{w} sum hhsize", g["hhsize"].sum(), sth.loc[w, "hhsize_sum"]); row("B", f"{w} sum household weight", g["wt"].sum(), sth.loc[w, "sum_wt_hh"], 1e-9)
        if logf.exists(): (LOGS / "stata_checks.log").write_text(logf.read_text()); logf.unlink()
    else:
        report.append(f"Stata run produced no output (rc={r.returncode}); see {logf}"); fails += 1
else:
    report.append("Stata not found on this machine -- section B skipped."); log.warning("Stata not found; skipping B")
report += ["", "## C. Household / person consistency", "", "| section | statistic | Python | reference | result |", "|---|---|---:|---:|---|"]
# AHS 2017 report table 2: 16,057 agricultural households interviewed (DOCUMENTATION.md)
if (hh["wave"] == "2017").any(): row("C", "2017 households vs report table 2 (16,057)", int((hh["wave"] == "2017").sum()), 16_057)
for w, g in hh.groupby("wave", sort=False):
    p = person[person.wave == w]
    row("C", f"{w} sum hhsize == person rows", g["hhsize"].sum(), len(p)); row("C", f"{w} households == distinct hhid in person file", len(g), p["hhid"].nunique()); row("C", f"{w} household rows unique", g["hhid"].nunique(), len(g))
report += ["", f"**{fails} check(s) failed.**" if fails else "**All checks passed.**"]
(LOGS / "checks_report.md").write_text("\n".join(report)); log.info("\n" + "\n".join(report))
if fails: sys.exit(f"{fails} check(s) failed -- see logs/checks_report.md")
log.info("03_checks done")
