"""
04_codebook.py -- AHS: generate CODEBOOK.md (+ codebook_<file>.csv) for every file in 3_Final/.

Per variable: label, storage type, value labels (first few), non-missing count per wave, the
source per wave recorded by 01_clean (person/household files), version decisions and label
variants recorded by 02_merge.
"""
import json
import pandas as pd
from ahs_helpers import paths, get_logger, read_dta, read_meta, LOGS, HERE

log = get_logger("04_codebook"); P = paths()
align = json.load(open(LOGS / "merge_alignment.json"))
metas = {f.stem.replace("clean_", "").replace("_meta", ""): json.load(open(f)) for f in LOGS.glob("clean_*_meta.json")}

def codebook(fname, info):
    df, vl, vv = read_dta(P["final"] / fname); m = read_meta(P["final"] / fname); types = m.readstat_variable_types
    waves = list(dict.fromkeys(df["wave"].tolist())) if "wave" in df else ["all"]
    nn = df.groupby("wave").count() if "wave" in df else None
    decisions = info.get("decisions", {}); rows = []
    unit = info.get("unit", "")
    for c in df.columns:
        base = next((b for b, d in decisions.items() if c in d.get("versions", {})), c)
        d = decisions.get(base, {}); vers = d.get("versions", {}); ws_here = vers.get(c, [])
        labs = {w: l for w, l in (d.get("labels_by_wave") or {}).items() if w in ws_here}
        variants = "; ".join(f"{w}: {l[:50]}" for w, l in labs.items() if l and l != d.get("reference_label")) if len(set(labs.values())) > 1 else ""
        others = ", ".join(f"{n} ({', '.join(g)})" for n, g in vers.items() if n != c) if len(vers) > 1 else ""
        src = "; ".join(f"{w}: {metas[w][unit]['source'][c]}" for w in ws_here if w in metas and unit in metas[w] and c in metas[w][unit].get("source", {}))
        vlab = vv.get(c, {}); vtxt = ", ".join(f"{k}={v}" for k, v in list(vlab.items())[:5]) + (" …" if len(vlab) > 5 else "")
        conf = info.get("value_label_conflicts", {}).get(c)
        rows.append({"variable": c, "label": vl.get(c) or "", "type": types.get(c, ""), "value_labels": vtxt, "n_value_labels": len(vlab),
                     **{f"n_{w}": int(nn.loc[w, c]) if nn is not None and w in nn.index and c in nn.columns else len(df) for w in waves},
                     "source": src, "versions": others, "label_variants": variants, "value_label_conflicts": json.dumps(conf) if conf else ""})
    cb = pd.DataFrame(rows); cb.to_csv(HERE / f"codebook_{fname[:-4]}.csv", index=False)
    md = [f"## `{fname}` — one row per {unit}", "", f"{len(df):,} rows × {df.shape[1]} variables. Waves: {', '.join(waves)}.", "",
          "| variable | label | type | value labels | " + " | ".join(f"N {w}" for w in waves) + " | notes |", "|---|---|---|---|" + "---:|" * len(waves) + "---|"]
    for r in rows:
        notes = [x for x in (("source: " + r["source"]) if r["source"] else "", ("other versions: " + r["versions"]) if r["versions"] else "",
                             ("label variants — " + r["label_variants"]) if r["label_variants"] else "",
                             ("value-label text conflicts: " + r["value_label_conflicts"]) if r["value_label_conflicts"] else "") if x]
        md.append("| `" + r["variable"] + "` | " + r["label"].replace("|", "/") + " | " + str(r["type"]) + " | " + r["value_labels"].replace("|", "/") +
                  " | " + " | ".join(f"{r[f'n_{w}']:,}" for w in waves) + " | " + "; ".join(notes).replace("|", "/") + " |")
    return md

out = ["# AHS codebook", "", "Generated by `04_codebook.py` from `3_Final/`. Do not hand-edit; see `DECISIONS.md` for the reasoning.", "",
       "Key block (identical names in every NISR dataset): `survey year wave sample prov dist urban cluster hhid pid sex age wt wt_hh`.",
       f"Alignment rule: waves are grouped into versions of a variable by label similarity (token Jaccard ≥ {align['threshold']}); the largest group keeps the name, "
       "the others are `<name>_v2`, `_v3` …. Value labels are the union within a version; where the same code had different text the most recent wave's text is kept and the conflict listed.", "",
       "Files: " + ", ".join(f"`{f}` ({i.get('unit')}, {i['rows']:,} rows)" for f, i in align["files"].items()), ""]
for fname, info in align["files"].items():
    out += codebook(fname, info) + [""]
(HERE / "CODEBOOK.md").write_text("\n".join(out)); log.info("wrote CODEBOOK.md and codebook_*.csv for %d files", len(align["files"]))
