"""
03_checks.py -- EC: independent verification of 3_Final/EC_pooled_establishment.dta -> logs/checks_report.md
  A. Python vs raw-file row counts (no prior processed outputs existed)
  B. Python vs Stata 17 recomputation on the written file
  C. Establishment and worker totals vs NISR's published EC reports
"""
import json, os, shutil, subprocess, sys
import pandas as pd
from ec_helpers import paths, get_logger, read_dta, read_meta, LOGS, HERE

log = get_logger("03_checks"); P = paths()
report = ["# EC checks report", "", "Generated by 03_checks.py.", ""]; fails = 0
def row(section, name, ours, ref, tol=0.0):
    global fails
    ok = None if ref is None else abs(float(ours) - float(ref)) <= tol * max(1.0, abs(float(ref)))
    fails += (ok is False)
    report.append(f"| {section} | {name} | {ours:,.0f} | {'' if ref is None else f'{ref:,.0f}'} | {'PASS' if ok else ('n/a' if ok is None else '**FAIL**')} |")

cols = [c for c in ["year", "wt", "dist", "sector", "urban", "estid", "s04", "total_workers", "total_emp2", "q20"] if c in read_meta(P["final"] / "EC_pooled_establishment.dta").column_names]
est, _, _ = read_dta(P["final"] / "EC_pooled_establishment.dta", usecols=cols)
ours = {int(y): {"n": len(g), "sum_wt": g["wt"].sum(), "n_dist": g["dist"].nunique(), "urban": int((g["urban"] == 1).sum()),
                 "workers": float(g["total_workers"].sum()) if "total_workers" in g and g["total_workers"].notna().any() else None,
                 "working": int((g["s04"] == 1).sum()) if "s04" in g else None} for y, g in est.groupby("year")}

report += ["## A. Pooled file vs raw files as shipped", "", "| section | statistic | Python | reference | result |", "|---|---|---:|---:|---|"]
bench = json.load(open(LOGS / "benchmark_old_stata.json"))
for f in bench["files"]: row("A", f"{f['year']} rows", ours[f["year"]]["n"], f["n_rows"])

report += ["", "## B. Stata 17 recomputation from the written .dta file", ""]
stata = "/Applications/Stata/StataMP.app/Contents/MacOS/stata-mp"
if not os.path.exists(stata): stata = shutil.which("stata-mp") or shutil.which("stata")
if stata:
    do, out = HERE / "stata_checks.do", LOGS / "stata_checks.csv"
    do.write_text(f'''* stata_checks.do -- recompute EC check statistics in Stata (written by 03_checks.py)
clear all
set more off
use year wt dist urban estid total_workers using "{P["final"] / "EC_pooled_establishment.dta"}", clear
gen long one = 1
gen byte urb = urban == 1
bysort year dist: gen byte first_dist = _n == 1
collapse (sum) n=one sum_wt=wt urban=urb n_dist=first_dist workers=total_workers, by(year)
export delimited using "{out}", replace
''')
    r = subprocess.run([stata, "-q", "-b", "do", str(do)], cwd=str(HERE), capture_output=True, text=True)
    logf = HERE / "stata_checks.log"
    if out.exists():
        st = pd.read_csv(out).set_index("year")
        report += ["| section | statistic | Python | Stata | result |", "|---|---|---:|---:|---|"]
        for y in sorted(ours):
            o, s = ours[y], st.loc[y]
            row("B", f"{y} rows", o["n"], s["n"]); row("B", f"{y} sum wt", o["sum_wt"], s["sum_wt"], 1e-9); row("B", f"{y} urban establishments", o["urban"], s["urban"]); row("B", f"{y} districts", o["n_dist"], s["n_dist"])
            if o["workers"] is not None: row("B", f"{y} total workers", o["workers"], s["workers"])
        if logf.exists(): (LOGS / "stata_checks.log").write_text(logf.read_text()); logf.unlink()
    else:
        report.append(f"Stata run produced no output (rc={r.returncode}); see {logf}"); fails += 1
else:
    report.append("Stata not found on this machine -- section B skipped."); log.warning("Stata not found; skipping B")

# ---- C. published figures (zz_Reports: EC 2011 report p.?, EC 2014, 2017, 2020 reports; 2023 report not held)
PUB = {"2011 establishments enumerated (2014 project document: 127,662)": (ours[2011]["n"], 127_662, 0),
       "2011 operating establishments (report: 123,526)": (ours[2011]["working"], 123_526, 0.01),
       "2014 weighted establishments (report: 154,236)": (ours[2014]["sum_wt"], 154_236, 0.001),
       "2017 establishments (report: 190,288)": (ours[2017]["n"], 190_288, 0),
       "2020 establishments (report: 232,283)": (ours[2020]["n"], 232_283, 0)}
report += ["", "## C. Against NISR published EC totals", "", "| section | statistic | Python | published | result |", "|---|---|---:|---:|---|"]
for k, (o, ref, tol) in PUB.items(): row("C", k, o, ref, tol)
report += ["", f"**{fails} check(s) failed.**" if fails else "**All checks passed.**"]
(LOGS / "checks_report.md").write_text("\n".join(report)); log.info("\n" + "\n".join(report))
if fails: sys.exit(f"{fails} check(s) failed -- see logs/checks_report.md")
log.info("03_checks done")
